### ISSUE TITLE
EOFError in callpeak_cmd.py

### ISSUE THREAD

**Issue by sitag** [taoliu/MACS#105]
I am running MACS2 (version:macs2 2.1.0.20150731) as ```Command line: callpeak -t $TREAT -c $CONTROL -f BAM -g hs -n ./H3K27ac_macs2.v.control -B -p 0.01```
and it fails with:

    INFO  @ Wed, 09 Dec 2015 15:53:34: #3   Pileup will be based on sequencing depth in control. 
    INFO  @ Wed, 09 Dec 2015 15:53:34: #3 Call peaks for each chromosome... 
    Traceback (most recent call last):
      File "/home/bin/anaconda/bin/macs2", line 614, in <module>
        main()
      File "/home/bin/anaconda/bin/macs2", line 56, in main
        run( args )
      File "/home/bin/anaconda/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 261, in run
        peakdetect.call_peaks()
      File "MACS2/PeakDetect.pyx", line 105, in MACS2.PeakDetect.PeakDetect.call_peaks (MACS2/PeakDetect.c:1632)
      File "MACS2/PeakDetect.pyx", line 251, in MACS2.PeakDetect.PeakDetect.__call_peaks_w_control (MACS2/PeakDetect.c:3172)
      File "MACS2/IO/CallPeakUnit.pyx", line 857, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks (MACS2/IO/CallPeakUnit.c:12297)
      File "MACS2/IO/CallPeakUnit.pyx", line 911, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks (MACS2/IO/CallPeakUnit.c:12049)
      File "MACS2/IO/CallPeakUnit.pyx", line 966, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__chrom_call_peak_using_certain_criteria (MACS2/IO/CallPeakUnit.c:12455)
      File "MACS2/IO/CallPeakUnit.pyx", line 461, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome (MACS2/IO/CallPeakUnit.c:6457)
    EOFError

Not sure what's going on with this. Any obvious places to start tracking this down?

**Comment by taoliu** [comment]
Yes. At this step, MACS2 tries to load a temporary cache file (e.g. /tmp/something for linux) containing the precomputed pileup values for a chromosome. It seems somehow the file is empty (either cleaned by system or other unexpected thing happened). Did you see such error again and again? I think I have to make this feature of loading temporary cache more stable...

**Comment by sitag** [comment]
It was running out of space in `/tmp` . I think there was a pull request to address this. Looks like it's taken care of.

**Comment by taoliu** [comment]
@sitag unfortunately, I noticed that pull request after I released the newest version yesterday. If you need that patch, you can download the current MACS2 source code from github then install MACS2. But you need to have Cython installed, and convert MACS2 pyx files to C -- using the setup_w_cython.py command.

**Comment by taoliu** [comment]
Closed. Reopen if needed.
