### ISSUE TITLE
error: undefined symbol __log10_finite

### ISSUE THREAD

**Issue by biocyberman** [taoliu/MACS#115]
I am tryint to run the following command and got the error. I guess I need to install additional libraries but I don't know which one. 

```bash
macs2 callpeak -t treatment.bam --broad -n
 "test" -f BAM -g 1949947921 --outdir macs2 
Traceback (most recent call last):
  File "~/bin/opt/anaconda/envs/pytools_env/bin/macs2", line 617, in <module>
    main()
  File "/~/bin/opt/anaconda/envs/pytools_env/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "~/bin/opt/anaconda/envs/pytools_env/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module
>
    from MACS2.OptValidator import opt_validate
  File "~/bin/opt/anaconda/envs/pytools_env/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module
>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "MACS2/IO/Parser.pyx", line 27, in init MACS2.IO.Parser (MACS2/IO/Parser.c:21821)
  File "MACS2/IO/FixWidthTrack.pyx", line 31, in init MACS2.IO.FixWidthTrack (MACS2/IO/FixWidthTrack.c:20307)
  File "MACS2/Pileup.pyx", line 24, in init MACS2.Pileup (MACS2/Pileup.c:13248)
ImportError: ~/bin/opt/anaconda/envs/pytools_env/lib/python2.7/site-packages/MACS2/IO/BedGraph.so: undefined symbol
: __log10_finite

```

**Comment by biocyberman** [comment]
After searching the net for a while, I found a workaround by disabling `libm.so*` under `anaconda/envs/pytools_env/lib/`. The bug goes to `anaconda` then.

**Comment by Portulaca666** [comment]
So  how to  disabling libm.so* under anaconda/envs/pytools_env/lib/.  ?please help me
