### ISSUE TITLE
Python int too large to convert to C long

### ISSUE THREAD

**Issue by junxiW** [taoliu/MACS#142]
Hi, all,

Just ran MACS2 (2.1.1.20160309) using -f BAM and got this error:

WARNING @ Thu, 18 Aug 2016 17:07:57: #2 Since the d (85) calculated from paired-peaks are smaller than 2*tag length, it may be influenced by unknown sequencing problem! 
WARNING @ Thu, 18 Aug 2016 17:07:57: #2 You may need to consider one of the other alternative d(s): 85,488,546 
WARNING @ Thu, 18 Aug 2016 17:07:57: #2 You can restart the process with --nomodel --extsize XXX with your choice or an arbitrary number. Nontheless, MACS will continute computing. 
INFO  @ Thu, 18 Aug 2016 17:07:57: #3 Call peaks... 
Traceback (most recent call last):
  File "/home/junxi/.local/bin/macs2", line 617, in <module>
    main()
  File "/home/junxi/.local/bin/macs2", line 57, in main
    run( args )
  File "/home/junxi/.local/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 264, in run
    peakdetect.call_peaks()
  File "MACS2/PeakDetect.pyx", line 105, in MACS2.PeakDetect.PeakDetect.call_peaks (MACS2/PeakDetect.c:1632)
  File "MACS2/PeakDetect.pyx", line 157, in MACS2.PeakDetect.PeakDetect.__call_peaks_w_control (MACS2/PeakDetect.c:1942)
OverflowError: Python int too large to convert to C long

Have you any thoughts? Thanks!

PS: the version of python is 2.7.12.

**Comment by taoliu** [comment]
Hi Junxi,

I saw such errors reported several times, such as #67, #102, and #106. It seems it is related to C and the operating system. Could you share me the information about the version of your C library and OS?

Best,
Tao

**Comment by junxiW** [comment]
Hi Tao,

my OS is ubuntu 16.04.1 LTS.

But I'm not sure the version of  my C library. I've tried to run the
commend: ldd --version and get the following message:

ldd (Ubuntu GLIBC 2.23-0ubuntu3) 2.23

Otherwise I've also tried the commend: apt-cache show libc6, then the
message is :

Package: libc6
Priority: required
Section: libs
Installed-Size: 9584
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Architecture: i386
Source: glibc
Version: 2.23-0ubuntu3
Replaces: libc6-i386, libc6-xen
Provides: libc6-i686, libc6-xen
Depends: libgcc1
Suggests: glibc-doc, debconf | debconf-2.0, locales
Conflicts: libc6-xen
Breaks: hurd (<< 1:0.5.git20140203-1), libtirpc1 (<< 0.2.3), locales (<<
2.23), locales-all (<< 2.23), nscd (<< 2.23)
Filename: pool/main/g/glibc/libc6_2.23-0ubuntu3_i386.deb
Size: 2269702
MD5sum: a45c39d770bc63cdffcc137151ef6cc7
SHA1: c93a132c90c044bfa57c9dc02fdc4acd9ce7055f
SHA256: 38200f93d7ed961421eada598e8e96a6428cc1a22c4b7a7a2242a9b240c7c1a0
Description-en: GNU C Library: Shared libraries
 Contains the standard libraries that are used by nearly all programs on
 the system. This package includes shared versions of the standard C library
 and the standard math library, as well as many others.
Description-md5: fc3001b0b90a1c8e6690b283a619d57f
Multi-Arch: same
Homepage: http://www.gnu.org/software/libc/libc.html
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 5y
Task: minimal

I hope it'll be useful to you.

Kind regards.
Junxi

2016-08-18 22:10 GMT+02:00 Tao Liu (τν) <notifications@github.com>:

**Comment by taoliu** [comment]
Hi Junxi,

I noticed that the 'architecture' is i386 which means the library is for 32bit system. This might be the main reason why it said 'Python int too large'.  I recommend you re-install MACS2 in a 64bit system and try again.  As for Ubuntu, it means the 'amd64' version.

Best,
Tao

**Comment by junxiW** [comment]
Hi Tao,

You're right. I've reinstalled MACS2 in the 64bit system. Now everything is
in order.

If it's possible, please tell the other Ubuntu-users that MACS2 is just for
64 bit system. Thank you very much.

Kind regards,
Junxi


2016-08-19 18:14 GMT+02:00 Tao Liu (τν) <notifications@github.com>:
