### ISSUE TITLE
MACS2 ImportError: No module named filterdup_cmd

### ISSUE THREAD

**Issue by Phil-T** [taoliu/MACS#154]
I keep getting the following error when using MACS2:
Input: macs2 filterdup -i 1.sam -o 1.filter.sam
output:
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 617, in <module>
    main()
  File "/usr/local/bin/macs2", line 88, in main
    from MACS2.filterdup_cmd import run
ImportError: No module named filterdup_cmd

I've tried uninstalling, reinstalling, etc etc - nothing works. Also verified filterdup is present.

Please help.

**Comment by Phil-T** [comment]
Sorry to have posted this - I didn't add macs2 to my pythonpath or path in my bashrc. I did this, and the issue resolved.
