### ISSUE TITLE
ATAC macs14 peak calling 

### ISSUE THREAD

**Issue by kminie** [taoliu/MACS#157]
I am facing following error while using macs14 :8ball: 

Traceback (most recent call last):
  File "/usr/local/bin/macs14", line 366, in <module>
    main()
  File "/usr/local/bin/macs14", line 60, in main
    (treat, control) = load_tag_files_options (options)
  File "/usr/local/bin/macs14", line 338, in load_tag_files_options
    treat = tp.build_fwtrack()
  File "/usr/local/lib/python2.7/dist-packages/MACS14/IO/Parser.py", line 812, in build_fwtrack
    (chrid,fpos,strand) = self.__fw_binary_parse(fread(entrylength))                    
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 332, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xbf9b068b != 0x7494add5L

Can any one help me to solve this

**Comment by zhanxw** [comment]
I guess your input file is broken?
Please check your bam files are complete.

**Comment by taoliu** [comment]
Agree with @zhanxw . Also, I suggest you to use MACS2 to call ATAC-Seq peaks since MACS2 is capable of dealing with PE data.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
