### ISSUE TITLE
Error with --keep-dup

### ISSUE THREAD

**Issue by paulicm-UCD** [taoliu/MACS#163]
Dear Tao,

I tried to use --keep-dup all and got this error:

INFO  @ Sat, 12 Nov 2016 12:10:38: #3 Call peaks... 
Traceback (most recent call last):
  File "/usr/bin/macs2", line 370, in <module>
    main()
  File "/usr/bin/macs2", line 193, in main
    if t1 > c1:
UnboundLocalError: local variable 't1' referenced before assignment

My script was:
module load macs2/2.1.0.20140616
macs2 callpeak -t x.bam -c input.bam -f BAM -g hs -n x_vs_input -B --keep-dup all -q 0.01

When using --keep-all auto, I had no errors. Could you please advice re: usage for -keep-dup all?
Thanks in advance,
Pauli

**Comment by taoliu** [comment]
Hi Pauli,

Could you upgrade MACS2 to the recent version to see if the problem is still there?

Best,
Tao

**Comment by paulicm-UCD** [comment]
Hi Tao,
I just had tried  macs2/2.1.1.20160309  and got the same error:

INFO  @ Thu, 08 Dec 2016 13:15:27: #3 Call peaks... 
Traceback (most recent call last):
  File "/usr/bin/macs2", line 370, in <module>
    main()
  File "/usr/bin/macs2", line 193, in main
    if t1 > c1:
UnboundLocalError: local variable 't1' referenced before assignment

Thanks,

Pauli

**Comment by taoliu** [comment]
Hi @paulicm-UCD, sorry for a very late followup. It seems like you were keeping running a 'macs2' script from system folder '/usr/bin/macs2' which you may not have permission to update. I suspect that that script was from an unknown older installation because currently there is no 't1>c1' in macs2 script at line 193. And you new updates were at different location so you need to set linux environment correctly.
