### ISSUE TITLE
macs2 callpeak error: ValueError: read length must be positive or -1

### ISSUE THREAD

**Issue by YungChihLai** [taoliu/MACS#166]
Hi,

I use macs2 to peak call ATAC-Seq 40 bp paired-end reads, and get an error message: ValueError: read length must be positive or -1 (the detail as the below). Could you help me? Many thanks.

Best,

Gary

gary > macs2 callpeak -t RA_G7_7_woChrM.bam --format AUTO --gsize 930000000 --keep-dup 1 --outdir RA_G7_7_woChrM --name RA_G7_7_woChrM --verbose 3 --nomodel --shift 50 --extsize 100 --qvalue 0.00000001 --cutoff-analysis --call-summits
INFO  @ Sat, 10 Dec 2016 13:33:18: 
# Command line: callpeak -t RA_G7_7_woChrM.bam --format AUTO --gsize 930000000 --keep-dup 1 --outdir RA_G7_7_woChrM --name RA_G7_7_woChrM --verbose 3 --nomodel --shift 50 --extsize 100 --qvalue 0.00000001 --cutoff-analysis --call-summits
# ARGUMENTS LIST:
# name = RA_G7_7_woChrM
# format = AUTO
# ChIP-seq file = ['RA_G7_7_woChrM.bam']
# control file = None
# effective genome size = 9.30e+08
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-08
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Searching for subpeak summits is on
 
INFO  @ Sat, 10 Dec 2016 13:33:18: #1 read tag files... 
INFO  @ Sat, 10 Dec 2016 13:33:18: #1 read treatment tags... 
DEBUG @ Sat, 10 Dec 2016 13:33:18: Testing format BAM 
INFO  @ Sat, 10 Dec 2016 13:33:18: Detected format is: BAM 
INFO  @ Sat, 10 Dec 2016 13:33:18: * Input file is gzipped. 
INFO  @ Sat, 10 Dec 2016 13:33:22:  1000000 
INFO  @ Sat, 10 Dec 2016 13:33:26:  2000000 
INFO  @ Sat, 10 Dec 2016 13:33:30:  3000000 
INFO  @ Sat, 10 Dec 2016 13:33:35:  4000000 
INFO  @ Sat, 10 Dec 2016 13:33:39:  5000000 
INFO  @ Sat, 10 Dec 2016 13:33:44:  6000000 
INFO  @ Sat, 10 Dec 2016 13:33:48:  7000000 
INFO  @ Sat, 10 Dec 2016 13:33:53:  8000000 
INFO  @ Sat, 10 Dec 2016 13:33:57:  9000000 
INFO  @ Sat, 10 Dec 2016 13:34:02:  10000000 
INFO  @ Sat, 10 Dec 2016 13:34:07:  11000000 
INFO  @ Sat, 10 Dec 2016 13:34:11:  12000000 
INFO  @ Sat, 10 Dec 2016 13:34:15:  13000000 
INFO  @ Sat, 10 Dec 2016 13:34:20:  14000000 
INFO  @ Sat, 10 Dec 2016 13:34:24:  15000000 
INFO  @ Sat, 10 Dec 2016 13:34:29:  16000000 
INFO  @ Sat, 10 Dec 2016 13:34:33:  17000000 
INFO  @ Sat, 10 Dec 2016 13:34:38:  18000000 
INFO  @ Sat, 10 Dec 2016 13:34:42:  19000000 
INFO  @ Sat, 10 Dec 2016 13:34:46:  20000000 
INFO  @ Sat, 10 Dec 2016 13:34:50:  21000000 
INFO  @ Sat, 10 Dec 2016 13:34:53:  22000000 
INFO  @ Sat, 10 Dec 2016 13:34:57:  23000000 
INFO  @ Sat, 10 Dec 2016 13:35:01:  24000000 
INFO  @ Sat, 10 Dec 2016 13:35:05:  25000000 
INFO  @ Sat, 10 Dec 2016 13:35:10:  26000000 
INFO  @ Sat, 10 Dec 2016 13:35:14:  27000000 
INFO  @ Sat, 10 Dec 2016 13:35:18:  28000000 
INFO  @ Sat, 10 Dec 2016 13:35:22:  29000000 
INFO  @ Sat, 10 Dec 2016 13:35:26:  30000000 
INFO  @ Sat, 10 Dec 2016 13:35:30:  31000000 
INFO  @ Sat, 10 Dec 2016 13:35:34:  32000000 
INFO  @ Sat, 10 Dec 2016 13:35:38:  33000000 
INFO  @ Sat, 10 Dec 2016 13:35:42:  34000000 
INFO  @ Sat, 10 Dec 2016 13:35:46:  35000000 
INFO  @ Sat, 10 Dec 2016 13:35:51:  36000000 
INFO  @ Sat, 10 Dec 2016 13:35:55:  37000000 
INFO  @ Sat, 10 Dec 2016 13:35:59:  38000000 
Traceback (most recent call last):
  File "/Users/gary/anaconda/bin/macs2", line 614, in <module>
    main()
  File "/Users/gary/anaconda/bin/macs2", line 56, in main
    run( args )
  File "/Users/gary/anaconda/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 70, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/Users/gary/anaconda/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 396, in load_tag_files_options
    treat = tp.build_fwtrack()
  File "MACS2/IO/Parser.pyx", line 805, in MACS2.IO.Parser.BAMParser.build_fwtrack (MACS2/IO/Parser.c:11351)
  File "MACS2/IO/Parser.pyx", line 810, in MACS2.IO.Parser.BAMParser.build_fwtrack (MACS2/IO/Parser.c:11218)
  File "MACS2/IO/Parser.pyx", line 877, in MACS2.IO.Parser.BAMParser.__build_fwtrack_wo_pysam (MACS2/IO/Parser.c:12358)
ValueError: read length must be positive or -1

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
