### ISSUE TITLE
MACS2 error compilation 

### ISSUE THREAD

**Issue by rojasp** [taoliu/MACS#169]
Hi, I have problems to run macs2, when I compile the script, I have the next error 

Traceback (most recent call last):
  File "/home/projas/MACS2-2.1.1.20160309/bin/macs2", line 617, in <module>
    main()
  File "/home/projas/MACS2-2.1.1.20160309/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/home/projas/MACS2-2.1.1.20160309/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/home/projas/MACS2-2.1.1.20160309/MACS2/OptValidator.py", line 204
    options.argtxt += "# Using a custom scaling factor: %.2e\n" % (options.ratio)
                                                                                ^
TabError: inconsistent use of tabs and spaces in indentationTraceback (most recent call last):
  File "/home/projas/MACS2-2.1.1.20160309/bin/macs2", line 617, in <module>
    main()
  File "/home/projas/MACS2-2.1.1.20160309/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/home/projas/MACS2-2.1.1.20160309/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/home/projas/MACS2-2.1.1.20160309/MACS2/OptValidator.py", line 204
    options.argtxt += "# Using a custom scaling factor: %.2e\n" % (options.ratio)
                                                                                ^
TabError: inconsistent use of tabs and spaces in indentation

any help?

**Comment by jharenza** [comment]
I am also having issues installing this using miniconda3. I first thought it was a python error, having multiple versions installed, but it is not. I created a virtual environment and tried installing the 2015 version using conda install macs2 and got errors. I tried the 2016 version and got errors. I tried pip install and got errors. I read that there was a point in time in which cython was required to install and I tried that and got errors. All are listed below. I cannot fully install this anymore. What is wrong?

[2016-macs2.txt](https://github.com/taoliu/MACS/files/676368/2016-macs2.txt)
[2016-pip-install.txt](https://github.com/taoliu/MACS/files/676367/2016-pip-install.txt)
[2015-macs2.txt](https://github.com/taoliu/MACS/files/676369/2015-macs2.txt)
[2016-cython-install.txt](https://github.com/taoliu/MACS/files/676370/2016-cython-install.txt)

Thanks, 

Jo Lynne

**Comment by akjohnson** [comment]
For anybody with this issue: we saw this when my coworker was trying to run it using Python3 something instead of Python2.7, so check your python version

**Comment by taoliu** [comment]
Now the Python3 compatible MACS v2.2.4 has been released. Please reopen if the problem still exists in the new versions. Thanks!
