### ISSUE TITLE
AssertionError: slocal can't be smaller than d!

### ISSUE THREAD

**Issue by c5creative** [taoliu/MACS#171]
Greetings,

(Googling around wasn't too helpful, so I hope posting here is appropriate).

I'm trying to run a "simple" MACS2 job (MACS2 2.1.0 20150420 rc):
```
macs2 callpeak \
--name 'HA vs. WT' \
--treatment $CHIPDATA1 \
--control $CHIPCTRL1 \
--outdir $DIRECTORY \
--qvalue .01 \
--format BAMPE \
--gsize mm \
--tempdir $TMP_DIRECTORY
```
The output of the job is as follows:
```
Log -- Running PEAKCALL_MACS2 Job
Log -- =================
Log -- Created tmp directory
INFO  @ Tue, 17 Jan 2017 15:11:11: 
# Command line: callpeak --name HA vs. WT --treatment /home/user/data/Processed-Data/3259-MAM/05-samtools/Ali
gned_sample_3259-MAM-7.out.sorted.bam --control /home/user/data/Processed-Data/3259-MAM/05-samtools/Aligned_sample_32
59-MAM-8.out.sorted.bam --outdir 07-peakcall_macs2 --qvalue .01 --format BAMPE --gsize mm --tempdir 07-peakcall_macs2/te
mp
# ARGUMENTS LIST:
# name = Neurog3-HA vs. WT
# format = BAMPE
# ChIP-seq file = ['/home/user/data/Processed-Data/3259-MAM/05-samtools/Aligned_sample_3259-MAM-7.out.sorted.bam']
# control file = ['/home/user/data/Processed-Data/3259-MAM/05-samtools/Aligned_sample_3259-MAM-8.out.sorted.bam']
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
# Paired-End mode is on
INFO  @ Tue, 17 Jan 2017 15:11:11: #1 read fragment files... 
INFO  @ Tue, 17 Jan 2017 15:11:11: #1 read treatment fragments... 
INFO  @ Tue, 17 Jan 2017 15:11:30:  1000000 
INFO  @ Tue, 17 Jan 2017 15:11:48:  2000000 
INFO  @ Tue, 17 Jan 2017 15:12:06:  3000000 
...
...
...
INFO  @ Tue, 17 Jan 2017 15:44:11:  42000000 
INFO  @ Tue, 17 Jan 2017 15:44:37:  43000000 
INFO  @ Tue, 17 Jan 2017 15:45:23: #1 mean fragment size is determined as 1109 bp from treatment 
INFO  @ Tue, 17 Jan 2017 15:45:24: #1 note: mean fragment size in control is 1853 bp -- value ignored 
INFO  @ Tue, 17 Jan 2017 15:45:24: #1 fragment size = 1109 
INFO  @ Tue, 17 Jan 2017 15:45:24: #1  total fragments in treatment: 42552760 
INFO  @ Tue, 17 Jan 2017 15:45:24: #1 user defined the maximum fragments... 
INFO  @ Tue, 17 Jan 2017 15:45:24: #1 filter out redundant fragments by allowing at most 1 identical fragment(s) 
INFO  @ Tue, 17 Jan 2017 15:48:03: #1  fragments after filtering in treatment: 31036085 
INFO  @ Tue, 17 Jan 2017 15:48:03: #1  Redundant rate of treatment: 0.27 
INFO  @ Tue, 17 Jan 2017 15:48:03: #1  total fragments in control: 43232586 
INFO  @ Tue, 17 Jan 2017 15:48:03: #1 user defined the maximum fragments... 
INFO  @ Tue, 17 Jan 2017 15:48:03: #1 filter out redundant fragments by allowing at most 1 identical fragment(s) 
INFO  @ Tue, 17 Jan 2017 15:50:45: #1  fragments after filtering in control: 29065439 
INFO  @ Tue, 17 Jan 2017 15:50:45: #1  Redundant rate of control: 0.33 
INFO  @ Tue, 17 Jan 2017 15:50:45: #1 finished! 
INFO  @ Tue, 17 Jan 2017 15:50:45: #2 Build Peak Model... 
INFO  @ Tue, 17 Jan 2017 15:50:45: #2 Skipped... 
INFO  @ Tue, 17 Jan 2017 15:50:45: #2 Use 1109 as fragment length 
INFO  @ Tue, 17 Jan 2017 15:50:45: #3 Call peaks... 
Traceback (most recent call last):
  File "/home/user/bin/anaconda2/bin/macs2", line 617, in <module>
    main()
  File "/home/user/bin/anaconda2/bin/macs2", line 57, in main
    run( args )
  File "/home/user/bin/anaconda2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 264, in run
    peakdetect.call_peaks()
  File "MACS2/PeakDetect.pyx", line 105, in MACS2.PeakDetect.PeakDetect.call_peaks (MACS2/PeakDetect.c:1632)
  File "MACS2/PeakDetect.pyx", line 177, in MACS2.PeakDetect.PeakDetect.__call_peaks_w_control (MACS2/PeakDetect.c:2163)
AssertionError: slocal can't be smaller than d!
```
Any ideas on what I might be doing wrong?  Running out of ideas... 

Thanks!!!
JP

**Comment by tianping** [comment]
You used the default slocal value 1000bp. Your mean fragment length (d) 
is 1109bp. That's why it complains "slocal can't be smaller than d!". I 
think you can get through by setting --slocal to a value larger than 
1109, eg. 2000.


In addition, it seems to me that the fragment length is very long (for a 
ChIP-seq experiment). Just curious about (1)  Is it really ChIP-seq 
data? (2) How was the library sequenced? on what platform? (The fragment 
length seems too long for PE sequencing on Hiseq. Or, I am behind the 
times?)


Best,

Dejian

**Comment by c5creative** [comment]
Dejian - thanks very much for helping me understand the error/log combination.

Indeed, the fragment length seems very long. It _is_ a ChIP-Seq experiment and after checking the library QC gel, the fragments are ~300bp. Precipitated chromatin was used to prepare sequencing libraries using NEB DNA Ultra II reagents. Samples were sequenced at PE-75 using HiSeq 3000, targeting 30M reads per sample.

So something must be wrong upstream IMO. After the usual quality control/trimming, I aligned our reads via STAR. I did find a [reference](https://groups.google.com/d/msg/rna-star/E_mKqm9jDm0/ZINystrdWRQJ) that indicates that I need to look at my alignment parameters more closely for ChIP-Seq data/STAR.  I'll report back for others, in case I'm not the only to run into this issue. 

Again, many thanks! Very helpful!
JP

**Comment by tianping** [comment]
I read the reference you provided. Very interesting discussion. But I 
prefer bowtie2 rather than STAR for aligning ChIP-seq reads. Good luck! 
-Dejian

**Comment by tianping** [comment]
I read the reference you provided. Very interesting discussion. But I prefer bowtie2 rather than STAR for aligning ChIP-seq reads. Good luck! -Dejian

On 1/18/17 1:59 PM, JP Cartailler wrote:

Dejian - thanks very much for helping me understand the error/log combination.

Indeed, the fragment length seems very long. It is a ChIP-Seq experiment and after checking the library QC gel, the fragments are ~300bp. Precipitated chromatin was used to prepare sequencing libraries using NEB DNA Ultra II reagents. Samples were sequenced at PE-75 using HiSeq 3000, targeting 30M reads per sample.

So something must be wrong upstream IMO. After the usual quality control/trimming, I aligned our reads via STAR. I did find a reference<https://groups.google.com/d/msg/rna-star/E_mKqm9jDm0/ZINystrdWRQJ> that indicates that I need to look at my alignment parameters more closely for ChIP-Seq data/STAR. I'll report back for others, in case I'm not the only to run into this issue.

Again, many thanks! Very helpful!
JP
