### ISSUE TITLE
Import Error for Parser.so

### ISSUE THREAD

**Issue by chutxing** [taoliu/MACS#196]
I load module of macs2 in the cluster. But when I run macs2, it shows that 
Traceback (most recent call last):
  File "/isg/shared/apps/macs2/2.1.1.20160309/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.1.20160309', 'macs2')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/isg/shared/apps/macs2/2.1.1.20160309/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 617, in <module>
    
  File "/isg/shared/apps/macs2/2.1.1.20160309/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main
    
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 31, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/OptValidator.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/IO/Parser.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/IO/Parser.py", line 6, in __bootstrap__
ImportError: /home/CAM/jxing/.python-eggs/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg-tmp/MACS2/IO/Parser.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

I installed cython 0.24 but it didn't work all the time. I also use the PYTHON_CONFIGURE_OPTS= --enable-unicode=ucs4 to change the python interpreter.

**Comment by yuaner90** [comment]
Hi,
    I found the same issue when I run macs2, and I fixed through command line
$unset PYTHONPATH
$source activate anaconda-2.*

https://stackoverflow.com/questions/17386880/does-anaconda-create-a-separate-pythonpath-variable-for-each-new-environment
