### ISSUE TITLE
macs2 callpeak :  ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by juliechevalier** [taoliu/MACS#213]
Hi,

I have an intermitent problem with Macs2 callpeak when I use build model. It seems a problem with building model because I have no problem when I use --nomodel and a fixed extend size in the same sample
So I ran this command with MACS2 2.1.0.20151222 :
callpeak --name MACS2 -t treat.bam --format=BAM --gsize 2451960000 --bw=300 --ratio 1.0 --slocal 1000 --llocal 10000 --keep-dup 2 --bdg --pvalue 0.01
# ARGUMENTS LIST:
# name = MACS2
# format = BAM
# ChIP-seq file = ['treat.bam']
# control file = None
# effective genome size = 2.45e+09
# band width = 300
# model fold = [5, 50]
# pvalue cutoff = 1.00e-02
# qvalue will not be calculated and reported as -1 in the final output.
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
 
INFO  @ Fri, 15 Sep 2017 11:11:27: #1 read tag files...
INFO  @ Fri, 15 Sep 2017 11:11:27: #1 read treatment tags...
INFO  @ Fri, 15 Sep 2017 11:11:29:  1000000
INFO  @ Fri, 15 Sep 2017 11:11:31:  2000000
INFO  @ Fri, 15 Sep 2017 11:11:33:  3000000
...
...
...
INFO  @ Fri, 15 Sep 2017 11:13:00:  48000000
INFO  @ Fri, 15 Sep 2017 11:13:02:  49000000
INFO  @ Fri, 15 Sep 2017 11:13:03:  50000000
INFO  @ Fri, 15 Sep 2017 11:13:04: #1 tag size is determined as 16 bps
INFO  @ Fri, 15 Sep 2017 11:13:04: #1 tag size = 16
INFO  @ Fri, 15 Sep 2017 11:13:04: #1  total tags in treatment: 50000000
INFO  @ Fri, 15 Sep 2017 11:13:04: #1 user defined the maximum tags...
INFO  @ Fri, 15 Sep 2017 11:13:04: #1 filter out redundant tags at the same location and the same strand by allowing at most 2 tag(s)
INFO  @ Fri, 15 Sep 2017 11:13:10: #1  tags after filtering in treatment: 50000000
INFO  @ Fri, 15 Sep 2017 11:13:10: #1  Redundant rate of treatment: 0.00
INFO  @ Fri, 15 Sep 2017 11:13:10: #1 finished!
INFO  @ Fri, 15 Sep 2017 11:13:10: #2 Build Peak Model...
INFO  @ Fri, 15 Sep 2017 11:13:18: #2 number of paired peaks: 9006
INFO  @ Fri, 15 Sep 2017 11:13:18: start model_add_line...
INFO  @ Fri, 15 Sep 2017 11:13:31: start X-correlation...

Traceback (most recent call last):
  File "/data/galaxy-dist/tool_dependency/macs2/2.1.0.20151222/iuc/package_macs2_2_1_0_20151222/e1370f7d5e2f/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.0.20151222', 'macs2')
  File "/data/galaxy-dist/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/galaxy-dist/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/data/galaxy-dist/tool_dependency/macs2/2.1.0.20151222/iuc/package_macs2_2_1_0_20151222/e1370f7d5e2f/lib/python/MACS2-2.1.0.20151222-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 614, in <module>
   
  File "/data/galaxy-dist/tool_dependency/macs2/2.1.0.20151222/iuc/package_macs2_2_1_0_20151222/e1370f7d5e2f/lib/python/MACS2-2.1.0.20151222-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main
   
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 175, in run
  File "MACS2/PeakModel.pyx", line 108, in MACS2.PeakModel.PeakModel.__init__ (MACS2/PeakModel.c:2385)
  File "MACS2/PeakModel.pyx", line 150, in MACS2.PeakModel.PeakModel.build (MACS2/PeakModel.c:2953)
  File "MACS2/PeakModel.pyx", line 230, in MACS2.PeakModel.PeakModel.__paired_peak_model (MACS2/PeakModel.c:4209)
ValueError: max() arg is an empty sequence

Any idea ?

Thanks
Julie

**Comment by visze** [comment]
Hi,

I have a (I guess) the same problem with the actual version (2.1.2) installed via conda..

This is the error. Any suggestions? I can share the BAM if you like

```
INFO  @ Tue, 22 Jan 2019 16:16:40:  203000000 
INFO  @ Tue, 22 Jan 2019 16:16:46:  204000000 
INFO  @ Tue, 22 Jan 2019 16:16:54: #1 tag size is determined as 20 bps 
INFO  @ Tue, 22 Jan 2019 16:16:54: #1 tag size = 20.0 
INFO  @ Tue, 22 Jan 2019 16:16:54: #1  total tags in treatment: 204782922 
INFO  @ Tue, 22 Jan 2019 16:16:54: #1 user defined the maximum tags... 
INFO  @ Tue, 22 Jan 2019 16:16:54: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
INFO  @ Tue, 22 Jan 2019 16:16:59: #1  tags after filtering in treatment: 171842001 
INFO  @ Tue, 22 Jan 2019 16:16:59: #1  Redundant rate of treatment: 0.16 
INFO  @ Tue, 22 Jan 2019 16:16:59: #1 finished! 
INFO  @ Tue, 22 Jan 2019 16:16:59: #2 Build Peak Model... 
INFO  @ Tue, 22 Jan 2019 16:16:59: #2 looking for paired plus/minus strand peaks... 
INFO  @ Tue, 22 Jan 2019 16:17:15: #2 number of paired peaks: 18187 
INFO  @ Tue, 22 Jan 2019 16:17:15: start model_add_line... 
INFO  @ Tue, 22 Jan 2019 16:17:17: start X-correlation... 
Traceback (most recent call last):
  File ".snakemake/conda/afea0091/bin/macs2", line 622, in <module>
    main()
  File ".snakemake/conda/afea0091/bin/macs2", line 57, in main
    run( args )
  File ".snakemake/conda/afea0091/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 178, in run
    opt = options
  File "MACS2/PeakModel.pyx", line 108, in MACS2.PeakModel.PeakModel.__init__ (MACS2/PeakModel.c:2435)
  File "MACS2/PeakModel.pyx", line 150, in MACS2.PeakModel.PeakModel.build (MACS2/PeakModel.c:3007)
  File "MACS2/PeakModel.pyx", line 230, in MACS2.PeakModel.PeakModel.__paired_peak_model (MACS2/PeakModel.c:4263)
ValueError: max() arg is an empty sequence
```

**Comment by visze** [comment]
any update here?
