### ISSUE TITLE
MACS2 Set pValue to -1 and terrifies IDR

### ISSUE THREAD

**Issue by amirshams84** [taoliu/MACS#220]
Hi It seems MACS2 Set pValue for some peaks to -1 and IDR cannot accept that and crashed
have to convert all -1 to 0 and it worked

**Comment by amirshams84** [comment]
AB2955-L1_R1.trim.PE2SE.nodup.pr1.tn5.pf.500K.pval0.01.narrowPeak.gz
chr16 67192014 67192579 Peak_102120 34 . 3.17360 3.48800 1.21916 319
chr16 89923548 89923621 Peak_102121 34 . 3.17360 3.48800 1.21916 -1
chr16 2223989 2224074 Peak_102119 34 . 3.17360 3.48800 1.21916 8
chr14 102140051 102140159 Peak_102118 34 . 3.17360 3.48800 1.21916 66
chr14 100110943 100111138 Peak_102117 34 . 3.17360 3.48800 1.21916 17
chr13 82549279 82549524 Peak_102116 34 . 3.17360 3.48800 1.21916 101

**Comment by amirshams84** [comment]
usr/local/envs/bds_atac_py3/bin/idr --samples /gs6/users/shamsaddinisha/jfarber-20160119-E1/VA2.7+CCR6+CCR2+/hg38/peak/macs2/pseudo_reps/rep1/pr1/AB2955-L1_R1.trim.PE2SE.nodup.pr1.tn5.pf.500K.pval0.01.narrowPeak.gz /gs6/users/shamsaddinisha/jfarber-20160119-E1/VA2.7+CCR6+CCR2+/hg38/peak/macs2/pseudo_reps/rep1/pr2/AB2955-L1_R1.trim.PE2SE.nodup.pr2.tn5.pf.500K.pval0.01.narrowPeak.gz --peak-list /gs6/users/shamsaddinisha/jfarber-20160119-E1/VA2.7+CCR6+CCR2+/hg38/peak/macs2/rep1/AB2955-L1_R1.trim.PE2SE.nodup.tn5.pf.500K.pval0.01.narrowPeak.gz --input-file-type narrowPeak --output-file /gs6/users/shamsaddinisha/jfarber-20160119-E1/VA2.7+CCR6+CCR2+/hg38/peak/macs2/idr/pseudo_reps/rep1/VA2.7+CCR6+CCR2+_rep1-pr.unthresholded-peaks.txt --rank p.value --soft-idr-threshold 0.05 --plot --use-best-multisummit-IDR --log-output-file /gs6/users/shamsaddinisha/jfarber-20160119-E1/VA2.7+CCR6+CCR2+/hg38/peak/macs2/idr/pseudo_reps/rep1/VA2.7+CCR6+CCR2+_rep1-pr.IDR0.05.log.txt

Traceback (most recent call last):
File "/usr/local/envs/bds_atac_py3/bin/idr", line 4, in
import('pkg_resources').run_script('idr==2.0.3', 'idr')
File "/usr/local/envs/bds_atac_py3/lib/python3.5/site-packages/pkg_resources/init.py", line 748, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/local/envs/bds_atac_py3/lib/python3.5/site-packages/pkg_resources/init.py", line 1517, in run_script
exec(code, namespace, namespace)
File "/usr/local/envs/bds_atac_py3/lib/python3.5/site-packages/idr-2.0.3-py3.5-linux-x86_64.egg/EGG-INFO/scripts/idr", line 10, in
idr.idr.main()
File "/usr/local/envs/bds_atac_py3/lib/python3.5/site-packages/idr-2.0.3-py3.5-linux-x86_64.egg/idr/idr.py", line 840, in main
merged_peaks, signal_type = load_samples(args)
File "/usr/local/envs/bds_atac_py3/lib/python3.5/site-packages/idr-2.0.3-py3.5-linux-x86_64.egg/idr/idr.py", line 760, in load_samples
oracle_pks, args.use_nonoverlapping_peaks)
File "/usr/local/envs/bds_atac_py3/lib/python3.5/site-packages/idr-2.0.3-py3.5-linux-x86_64.egg/idr/idr.py", line 281, in merge_peaks
use_nonoverlapping_peaks=use_nonoverlapping_peaks)
File "/usr/local/envs/bds_atac_py3/lib/python3.5/site-packages/idr-2.0.3-py3.5-linux-x86_64.egg/idr/idr.py", line 223, in merge_peaks_in_contig
all_intervals.sort()
TypeError: unorderable types: NoneType() < int()

**Comment by amirshams84** [comment]
ARGUMENTS LIST:
name = /gs6/users/shamsaddinisha/jfarber-20160119-E1/VA2.7+CCR6+CCR2+/hg38/peak/macs2/pooled_pseudo_reps/ppr2/AB2955-L1_R1.trim.PE2SE.nodup.pr2.tn5_AB2959-L1_R1.trim.PE2SE.nodup.pr2.tn5.pf
format = BED
ChIP-seq file = ['/gs6/users/shamsaddinisha/jfarber-20160119-E1/VA2.7+CCR6+CCR2+/hg38/align/pooled_pseudo_reps/ppr2/AB2955-L1_R1.trim.PE2SE.nodup.pr2.tn5_AB2959-L1_R1.trim.PE2SE.nodup.pr2.tn5.tagAlign.gz']
control file = None
effective genome size = 2.70e+09
band width = 300
model fold = [5, 50]
pvalue cutoff = 1.00e-02
### qvalue will not be calculated and reported as -1 in the final output.
Larger dataset will be scaled towards smaller dataset.
Range for calculating regional lambda is: 10000 bps
Broad region calling is off
Searching for subpeak summits is on
MACS will save fragment pileup signal per million reads
