### ISSUE TITLE
Error with --nolamda option enabled

### ISSUE THREAD

**Issue by dimkonstanto** [taoliu/MACS#221]
Greetings,

I am facing some troubles when I am using --nolamda option:

macs2 callpeak -t CB9TUACXX_OATAC_TAS_17s005511-1-1_lane6_1_sequence.dup.bed -f BED --nomodel --nolambda --keep-dup all --shift 37 --extsize 73 -n peak_calling/nolambda_out

...

INFO  @ Wed, 15 Nov 2017 14:44:10:  50000000 
INFO  @ Wed, 15 Nov 2017 14:44:12:  51000000 
INFO  @ Wed, 15 Nov 2017 14:44:14:  52000000 
INFO  @ Wed, 15 Nov 2017 14:44:16:  53000000 
INFO  @ Wed, 15 Nov 2017 14:44:19:  54000000 
INFO  @ Wed, 15 Nov 2017 14:44:21:  55000000 
INFO  @ Wed, 15 Nov 2017 14:44:23:  56000000 
INFO  @ Wed, 15 Nov 2017 14:44:26: #1 tag size is determined as 49 bps 
INFO  @ Wed, 15 Nov 2017 14:44:26: #1 tag size = 49 
INFO  @ Wed, 15 Nov 2017 14:44:26: #1  total tags in treatment: 56122595 
INFO  @ Wed, 15 Nov 2017 14:44:26: #1 finished! 
INFO  @ Wed, 15 Nov 2017 14:44:26: #2 Build Peak Model... 
INFO  @ Wed, 15 Nov 2017 14:44:26: #2 Skipped... 
INFO  @ Wed, 15 Nov 2017 14:44:26: #2 Sequencing ends will be shifted towards 3' by 37 bp(s) 
INFO  @ Wed, 15 Nov 2017 14:44:26: #2 Use 73 as fragment length 
INFO  @ Wed, 15 Nov 2017 14:44:26: #3 Call peaks... 
INFO  @ Wed, 15 Nov 2017 14:44:26: # local lambda is disabled! 
INFO  @ Wed, 15 Nov 2017 14:44:26: #3 !!!! DYNAMIC LAMBDA IS DISABLED !!!! 
INFO  @ Wed, 15 Nov 2017 14:44:26: #3 Pre-compute pvalue-qvalue table... 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 614, in <module>
    main()
  File "/usr/local/bin/macs2", line 56, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/callpeak_cmd.py", line 261, in run
    peakdetect.call_peaks()
  File "MACS2/PeakDetect.pyx", line 110, in MACS2.PeakDetect.PeakDetect.call_peaks (MACS2/PeakDetect.c:1665)
  File "MACS2/PeakDetect.pyx", line 364, in MACS2.PeakDetect.PeakDetect.__call_peaks_wo_control (MACS2/PeakDetect.c:4714)
  File "MACS2/IO/CallPeakUnit.pyx", line 858, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks (MACS2/IO/CallPeakUnit.c:12340)
  File "MACS2/IO/CallPeakUnit.pyx", line 883, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks (MACS2/IO/CallPeakUnit.c:11717)
  File "MACS2/IO/CallPeakUnit.pyx", line 653, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_pvalue_qvalue_table (MACS2/IO/CallPeakUnit.c:9065)
  File "MACS2/IO/CallPeakUnit.pyx", line 496, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome (MACS2/IO/CallPeakUnit.c:7329)
TypeError: 'float' object cannot be interpreted as an index

while when I do not enable it, the program is run with no errors.

Any help would be appreciated.

**Comment by yuxinghai** [comment]
I meet the same problem in MACS2-2.1.0.20150420

**Comment by OscarBrock** [comment]
I've also encountered this problem. Is there a known solution?

**Comment by dimkonstanto** [comment]
Not yet from my side..

2018-07-11 23:52 GMT+03:00 OscarBrock <notifications@github.com>:

**Comment by Heroico** [comment]
Hi all,

I get the same error on MACS2. From looking around the web, this seems an obscure issue from numpy - many people reported fixing it by changing to different python/numpy/numerical libraries installation.

In my case this happened in a cluster environment with system-installed libraries.
I then used conda with python 3.7 and macs2 from bioconda and it worked.

**Comment by taoliu** [comment]
@Heroico Right. This is one of the major updates in recent macs2 releases -- to test under different environments. To install macs2 from bioconda definitely will make life easier/happier.
