### ISSUE TITLE
Some kind of memory error?

### ISSUE THREAD

**Issue by mezarque** [taoliu/MACS#232]
Hi there,

I'm running MACS2 to analyze some ATAC-Seq data. I have a genome size of 3.6GB or so, and around 10-50 million reads mapped using Bowtie2 per sample. For the smaller samples, MACS2 is succeeding just fine, but for the larger samples, I keep getting the error below.

I am running MACS2 on a SLURM cluster, using a single node with 20 cores and 512GB memory, so I'd be surprised if there wasn't enough memory to go around... Please let me know if there's some obvious thing I can do to solve this.

INFO  @ Thu, 01 Mar 2018 13:17:34: #1 mean fragment size is determined as 54 bp from treatment 
INFO  @ Thu, 01 Mar 2018 13:17:34: #1 fragment size = 54 
INFO  @ Thu, 01 Mar 2018 13:17:34: #1  total fragments in treatment: 79240199 
INFO  @ Thu, 01 Mar 2018 13:17:34: #1 finished! 
INFO  @ Thu, 01 Mar 2018 13:17:34: #2 Build Peak Model... 
INFO  @ Thu, 01 Mar 2018 13:17:34: #2 Skipped... 
INFO  @ Thu, 01 Mar 2018 13:17:34: #2 Use 54 as fragment length 
INFO  @ Thu, 01 Mar 2018 13:17:34: #3 Call peaks... 
INFO  @ Thu, 01 Mar 2018 13:17:34: #3 Pre-compute pvalue-qvalue table... 
Traceback (most recent call last):
  File "/clusterfs/vector/home/groups/software/sl-7.x86_64/modules/macs/2.1.1/bin/macs2", line 617, in <module>
    main()
  File "/clusterfs/vector/home/groups/software/sl-7.x86_64/modules/macs/2.1.1/bin/macs2", line 57, in main
    run( args )
  File "/clusterfs/vector/home/groups/software/sl-7.x86_64/modules/macs/2.1.1/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 264, in run
    peakdetect.call_peaks()
  File "MACS2/PeakDetect.pyx", line 110, in MACS2.PeakDetect.PeakDetect.call_peaks (MACS2/PeakDetect.c:1665)
  File "MACS2/PeakDetect.pyx", line 364, in MACS2.PeakDetect.PeakDetect.__call_peaks_wo_control (MACS2/PeakDetect.c:4714)
  File "MACS2/IO/CallPeakUnit.pyx", line 861, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks (MACS2/IO/CallPeakUnit.c:12334)
  File "MACS2/IO/CallPeakUnit.pyx", line 886, in MACS2.IO.CallPeakUnit.CallerFromAlignments.call_peaks (MACS2/IO/CallPeakUnit.c:11711)
  File "MACS2/IO/CallPeakUnit.pyx", line 656, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__cal_pvalue_qvalue_table (MACS2/IO/CallPeakUnit.c:9059)
  File "MACS2/IO/CallPeakUnit.pyx", line 483, in MACS2.IO.CallPeakUnit.CallerFromAlignments.__pileup_treat_ctrl_a_chromosome (MACS2/IO/CallPeakUnit.c:7032)
  File "MACS2/IO/PairedEndTrack.pyx", line 510, in MACS2.IO.PairedEndTrack.PETrackI.pileup_a_chromosome (MACS2/IO/PairedEndTrack.c:8254)
  File "MACS2/IO/PairedEndTrack.pyx", line 528, in MACS2.IO.PairedEndTrack.PETrackI.pileup_a_chromosome (MACS2/IO/PairedEndTrack.c:8045)
  File "MACS2/Pileup.pyx", line 661, in MACS2.Pileup.quick_pileup (MACS2/Pileup.c:9292)
  File "MACS2/Pileup.pyx", line 698, in MACS2.Pileup.quick_pileup (MACS2/Pileup.c:8468)
MemoryError

**Comment by zyqzyqzyq** [comment]
excuse me ,I have the same error as yours ,have you solve the problem?

**Comment by taoliu** [comment]
Related to #313 ?
