### ISSUE TITLE
Macs2 Numpy Error

### ISSUE THREAD

**Issue by bauerbach95** [taoliu/MACS#252]
I recently downloaded macs2 from the bioconda channel using conda.

I tried to call peaks on a bedgraph file with the following command:
"macs2 bdgpeakcall -i atac_seq/ENCFF700NIW.bedgraph -o test.bed"

However, I received the following error:
"Traceback (most recent call last):
  File "/home/benauer/anaconda2/envs/conda_env/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.0.20150731', 'macs2')
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 614, in <module>
    
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 63, in main
    
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/MACS2/bdgpeakcall_cmd.py", line 23, in <module>
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/MACS2/IO/BedGraphIO.py", line 7, in <module>
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/MACS2/IO/BedGraphIO.py", line 6, in __bootstrap__
  File "MACS2/IO/BedGraphIO.pyx", line 22, in init MACS2.IO.BedGraphIO (MACS2/IO/BedGraphIO.c:2577)
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/MACS2/IO/BedGraph.py", line 7, in <module>
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/MACS2/IO/BedGraph.py", line 6, in __bootstrap__
  File "MACS2/IO/BedGraph.pyx", line 32, in init MACS2.IO.BedGraph (MACS2/IO/BedGraph.c:19103)
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/MACS2/IO/ScoreTrack.py", line 7, in <module>
  File "/home/benauer/anaconda2/envs/conda_env/lib/python2.7/site-packages/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg/MACS2/IO/ScoreTrack.py", line 6, in __bootstrap__
  File "numpy.pxd", line 155, in init MACS2.IO.ScoreTrack (MACS2/IO/ScoreTrack.c:31313)
ValueError: numpy.dtype has the wrong size, try recompiling"

Any idea of how to fix? Thanks.

**Comment by taoliu** [comment]
It seems that MACS2 (version 2.1.0.20150731) is no compiled well in bioconda. Suggestion is to download the source code from PIP then compile and install.
