### ISSUE TITLE
macs2 installation issues using pip

### ISSUE THREAD

**Issue by gsathishk** [taoliu/MACS#282]
I have been trying to install macs2 to run some jobs on hpc server, but still failing after multiple attempts to install. I used "pip install MACS2" and this is the error I get:

`tommy35@hpc-login3:~/project/NGStools pip install MACS2
Collecting MACS2
Requirement already satisfied: numpy>=1.6 in /auto/rcf-40/tommy35/.local/lib/python2.7/site-packages (from MACS2)
Installing collected packages: MACS2
Exception:
Traceback (most recent call last):
  File "/home/rcf-40/tommy35/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/rcf-40/tommy35/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/rcf-40/tommy35/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/rcf-40/tommy35/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/rcf-40/tommy35/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/rcf-40/tommy35/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/rcf-40/tommy35/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/rcf-40/tommy35/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/lib64/python2.7/site-packages/MACS2'
You are using pip version 9.0.3, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

I can't do 'sudo' since I am on hpc and I don't have permission to do that. 
I tried also `pip install macs2 --user` which successfully installed : `tommy35@hpc-login3:~ pip show macs2
Name: MACS2
Version: 2.1.2
Summary: Model Based Analysis for ChIP-Seq data
Home-page: http://github.com/taoliu/MACS/
Author: Tao Liu
Author-email: vladimir.liu@gmail.com
License: UNKNOWN
Location: /auto/rcf-40/tommy35/.local/lib/python2.7/site-packages
Requires: numpy`

But when I call macs2, I get no command error: 
`tommy35@hpc-login3:~ macs2
-bash: macs2: command not found` 

What do you suggest?

**Comment by taoliu** [comment]
Since you have successfully installed macs2 using 'pip ... --user', you should then set the environment variable `PATH` to include this path: `/auto/rcf-40/tommy35/.local/`:

`$ export PATH=/auto/rcf-40/tommy35/.local/:$PATH`

**Comment by taoliu** [comment]
Hi @gsathishk please let me know if the problem has been solved or it still exists. Thanks!
