### ISSUE TITLE
trapped in AttributeError: 'Namespace' object has no attribute 'maxgap'

### ISSUE THREAD

**Issue by ZihuaLiu666** [taoliu/MACS#286]
Hi Tao,

This afternoon I tried to conduct peak calling with MACS2 but I trapped in the problem below.

Here is my command line:
```
for i in SRR7759388 SRR7759389 SRR7759390
do
pkurun-cns 1 10 macs2 callpeak -t ${i}.sorted.bam -f BAM -p 0.0001 -g hs -n ${i} --outdir ./
done
```

AND the error info is 
```
Traceback (most recent call last):
  File "/lustre1/zihua/bin/macs2", line 617, in <module>
    main()
  File "/lustre1/zihua/bin/macs2", line 57, in main
    run( args )
  File "/lustre2/zihua/tools/Python-2.7.15/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 56, in run
    options = opt_validate( args )
  File "/lustre2/zihua/tools/Python-2.7.15/lib/python2.7/site-packages/MACS2/OptValidator.py", line 193, in opt_validate
    if options.maxgap:
AttributeError: 'Namespace' object has no attribute 'maxgap'
```

Please help me to fix the problem, many thanks!

**Comment by ZihuaLiu666** [comment]
> Hi Tao,
> 
> This afternoon I tried to conduct peak calling with MACS2 but I trapped in the problem below.
> 
> Here is my command line:
> 
> ```
> for i in SRR7759388 SRR7759389 SRR7759390
> do
> pkurun-cns 1 10 macs2 callpeak -t ${i}.sorted.bam -f BAM -p 0.0001 -g hs -n ${i} --outdir ./
> done
> ```
> 
> AND the error info is
> 
> ```
> Traceback (most recent call last):
>   File "/lustre1/zihua/bin/macs2", line 617, in <module>
>     main()
>   File "/lustre1/zihua/bin/macs2", line 57, in main
>     run( args )
>   File "/lustre2/zihua/tools/Python-2.7.15/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 56, in run
>     options = opt_validate( args )
>   File "/lustre2/zihua/tools/Python-2.7.15/lib/python2.7/site-packages/MACS2/OptValidator.py", line 193, in opt_validate
>     if options.maxgap:
> AttributeError: 'Namespace' object has no attribute 'maxgap'
> ```
> 
> Please help me to fix the problem, many thanks!

I have fixed the problem by myself...
Here are the solutions...
1. Delete the pre-existed MACS2 folder;
2. Delete the address of the site-packages of Python2 within the ~/.bashrc file;
3. Rerun the setup.py file in the MACS2 folder (please re-download MACS2 firstly). python2 setup.py install

Then, the newly installed MACS2 will find the /lustre2/zihua/tools/Python-2.7.15/lib/python2.7/site-packages automatically... and everything done...
