### ISSUE TITLE
call peaks error - struct.error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by AYYYang** [taoliu/MACS#288]
# Command line: callpeak -t filtered_H3K9ME3_MEIS1_NATIVE_A10.bam -f BAM -c input_Meis1_native_D02.bam -g mm --broad --broad-cutoff 0.1
# ARGUMENTS LIST:
# name = NA
# format = BAM
# ChIP-seq file = ['filtered_H3K9ME3_MEIS1_NATIVE_A10.bam']
# control file = ['input_Meis1_native_D02.bam']
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff for narrow/strong regions = 5.00e-02
# qvalue cutoff for broad/weak regions = 1.00e-01
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is on
# Paired-End mode is off
 
INFO  @ Wed, 08 May 2019 17:48:44: #1 read tag files... 
INFO  @ Wed, 08 May 2019 17:48:44: #1 read treatment tags... 
INFO  @ Wed, 08 May 2019 17:48:48:  1000000 
INFO  @ Wed, 08 May 2019 17:48:52:  2000000 
INFO  @ Wed, 08 May 2019 17:48:55:  3000000 
INFO  @ Wed, 08 May 2019 17:48:59:  4000000 
INFO  @ Wed, 08 May 2019 17:49:03:  5000000 
INFO  @ Wed, 08 May 2019 17:49:07:  6000000 
INFO  @ Wed, 08 May 2019 17:49:11:  7000000 
INFO  @ Wed, 08 May 2019 17:49:14:  8000000 
INFO  @ Wed, 08 May 2019 17:49:18:  9000000 
INFO  @ Wed, 08 May 2019 17:49:22:  10000000 
INFO  @ Wed, 08 May 2019 17:49:26:  11000000 
INFO  @ Wed, 08 May 2019 17:49:30:  12000000 
INFO  @ Wed, 08 May 2019 17:49:34:  13000000 
INFO  @ Wed, 08 May 2019 17:49:38:  14000000 
INFO  @ Wed, 08 May 2019 17:49:42:  15000000 
INFO  @ Wed, 08 May 2019 17:49:46:  16000000 
INFO  @ Wed, 08 May 2019 17:49:49:  17000000 
INFO  @ Wed, 08 May 2019 17:49:53:  18000000 
INFO  @ Wed, 08 May 2019 17:49:57:  19000000 
INFO  @ Wed, 08 May 2019 17:50:01:  20000000 
INFO  @ Wed, 08 May 2019 17:50:05:  21000000 
INFO  @ Wed, 08 May 2019 17:50:08:  22000000 
INFO  @ Wed, 08 May 2019 17:50:12:  23000000 
INFO  @ Wed, 08 May 2019 17:50:16:  24000000 
INFO  @ Wed, 08 May 2019 17:50:20:  25000000 
INFO  @ Wed, 08 May 2019 17:50:24:  26000000 
INFO  @ Wed, 08 May 2019 17:50:28:  27000000 
INFO  @ Wed, 08 May 2019 17:50:31:  28000000 
INFO  @ Wed, 08 May 2019 17:50:35:  29000000 
INFO  @ Wed, 08 May 2019 17:50:39:  30000000 
INFO  @ Wed, 08 May 2019 17:50:43:  31000000 
INFO  @ Wed, 08 May 2019 17:50:47:  32000000 
INFO  @ Wed, 08 May 2019 17:50:51:  33000000 
INFO  @ Wed, 08 May 2019 17:50:55:  34000000 
INFO  @ Wed, 08 May 2019 17:50:59:  35000000 
INFO  @ Wed, 08 May 2019 17:51:03:  36000000 
INFO  @ Wed, 08 May 2019 17:51:08:  37000000 
INFO  @ Wed, 08 May 2019 17:51:12:  38000000 
INFO  @ Wed, 08 May 2019 17:51:16:  39000000 
INFO  @ Wed, 08 May 2019 17:51:20:  40000000 
INFO  @ Wed, 08 May 2019 17:51:24:  41000000 
INFO  @ Wed, 08 May 2019 17:51:29:  42000000 
INFO  @ Wed, 08 May 2019 17:51:33:  43000000 
INFO  @ Wed, 08 May 2019 17:51:37:  44000000 
INFO  @ Wed, 08 May 2019 17:51:41:  45000000 
INFO  @ Wed, 08 May 2019 17:51:45:  46000000 
INFO  @ Wed, 08 May 2019 17:51:49:  47000000 
INFO  @ Wed, 08 May 2019 17:51:53:  48000000 
INFO  @ Wed, 08 May 2019 17:51:57:  49000000 
INFO  @ Wed, 08 May 2019 17:52:01:  50000000 
INFO  @ Wed, 08 May 2019 17:52:06:  51000000 
INFO  @ Wed, 08 May 2019 17:52:10:  52000000 
INFO  @ Wed, 08 May 2019 17:52:14:  53000000 
INFO  @ Wed, 08 May 2019 17:52:18:  54000000 
INFO  @ Wed, 08 May 2019 17:52:22:  55000000 
INFO  @ Wed, 08 May 2019 17:52:26:  56000000 
INFO  @ Wed, 08 May 2019 17:52:30:  57000000 
INFO  @ Wed, 08 May 2019 17:52:34:  58000000 
INFO  @ Wed, 08 May 2019 17:52:38:  59000000 
INFO  @ Wed, 08 May 2019 17:52:42:  60000000 
INFO  @ Wed, 08 May 2019 17:52:46:  61000000 
INFO  @ Wed, 08 May 2019 17:52:49:  62000000 
INFO  @ Wed, 08 May 2019 17:52:53:  63000000 
INFO  @ Wed, 08 May 2019 17:52:57:  64000000 
INFO  @ Wed, 08 May 2019 17:53:01:  65000000 
INFO  @ Wed, 08 May 2019 17:53:05:  66000000 
INFO  @ Wed, 08 May 2019 17:53:09:  67000000 
INFO  @ Wed, 08 May 2019 17:53:13:  68000000 
INFO  @ Wed, 08 May 2019 17:53:17:  69000000 
INFO  @ Wed, 08 May 2019 17:53:20:  70000000 
INFO  @ Wed, 08 May 2019 17:53:24:  71000000 
INFO  @ Wed, 08 May 2019 17:53:28:  72000000 
INFO  @ Wed, 08 May 2019 17:53:32:  73000000 
INFO  @ Wed, 08 May 2019 17:53:36:  74000000 
INFO  @ Wed, 08 May 2019 17:53:40:  75000000 
INFO  @ Wed, 08 May 2019 17:53:43:  76000000 
INFO  @ Wed, 08 May 2019 17:53:47:  77000000 
INFO  @ Wed, 08 May 2019 17:53:51:  78000000 
INFO  @ Wed, 08 May 2019 17:53:55:  79000000 
INFO  @ Wed, 08 May 2019 17:53:59:  80000000 
INFO  @ Wed, 08 May 2019 17:54:03: #1.2 read input tags... 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 622, in <module>
    main()
  File "/usr/local/bin/macs2", line 57, in main
    run( args )
  File "/Library/Python/2.7/site-packages/MACS2/callpeak_cmd.py", line 73, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/Library/Python/2.7/site-packages/MACS2/callpeak_cmd.py", line 411, in load_tag_files_options
    control = options.parser(options.cfile[0], buffer_size=options.buffer_size).build_fwtrack()
  File "MACS2/IO/Parser.pyx", line 876, in MACS2.IO.Parser.BAMParser.build_fwtrack (MACS2/IO/Parser.c:13658)
  File "MACS2/IO/Parser.pyx", line 889, in MACS2.IO.Parser.BAMParser.build_fwtrack (MACS2/IO/Parser.c:13066)
  File "MACS2/IO/Parser.pyx", line 862, in MACS2.IO.Parser.BAMParser.get_references (MACS2/IO/Parser.c:12582)
struct.error: unpack requires a string argument of length 4

**Comment by AYYYang** [comment]
I used samtools flagstat and samtools quickcheck to check my files, and they seem to be fine(quick check was silent and flagstat returned alignment stats), I was wondering what could be wrong?

**Comment by AYYYang** [comment]
Resolved at Biostars
