### ISSUE TITLE
Bug: Trouble with numpy using macs2 2.1.2

### ISSUE THREAD

**Issue by El-Castor** [taoliu/MACS#298]
Hi I have some trooble with my macs2 environment installed with conda. The source of the package it's in the channel bioconda and the version of macs2 is 2.1.2. The version of numpy is : 1.16.4 ( I've try with the 1.17 version but it's seems the same issues).

Here you have the error of macs2 : 

`
Traceback (most recent call last):
  File "/opt/share/FLOCAD/userspace/cpichot/miniconda3/envs/macs2TestNewInstall/bin/macs2", line 622, in <module>
    main()
  File "/opt/share/FLOCAD/userspace/cpichot/miniconda3/envs/macs2TestNewInstall/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/opt/share/FLOCAD/userspace/cpichot/miniconda3/envs/macs2TestNewInstall/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/opt/share/FLOCAD/userspace/cpichot/miniconda3/envs/macs2TestNewInstall/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
'
Do you have any idea to solved my problem ?  
thanks in advances

**Comment by taoliu** [comment]
I feel it's a compilation issue. MACS2 contain some Cython codes that have to be translated into C code. The translation depends on 1. Python version; 2. Cython version; 3. Numpy version. I think MACS2 has to be re-compiled (or the C code has to be regenerated in the new environment). The easiest way for me is to install MACS2 through PyPI system -- "pip install macs2". I don't use conda so can't comment.

**Comment by dawe** [comment]
Had the same issue yesterday, reinstallation of numpy from the same conda channel as MACS solved my issue

**Comment by taoliu** [comment]
Thank you Davide! @dawe
