### ISSUE TITLE
Cython.Compiler.Errors.CompileError: MACS2/IO/BedGraph.pyx of MACS (2.1.3.3)

### ISSUE THREAD

**Issue by KR-Chow** [taoliu/MACS#317]
**Describe the error**
Cython.Compiler.Errors.CompileError: MACS2/IO/BedGraph.pyx

**installation environment**
Anaconda2/4.2.0

**error detail**
```bash
(py2) [user@host MACS2]$ python2.7 setup.py install
Compiling MACS2/Prob.pyx because it changed.
Compiling MACS2/IO/Parser.pyx because it changed.
Compiling MACS2/Pileup.pyx because it changed.
Compiling MACS2/PeakModel.pyx because it changed.
Compiling MACS2/PeakDetect.pyx because it changed.
Compiling MACS2/Signal.pyx because it changed.
Compiling MACS2/IO/PeakIO.pyx because it changed.
Compiling MACS2/IO/BedGraphIO.pyx because it changed.
Compiling MACS2/IO/FixWidthTrack.pyx because it changed.
Compiling MACS2/IO/PairedEndTrack.pyx because it changed.
Compiling MACS2/IO/BedGraph.pyx because it changed.
Compiling MACS2/IO/ScoreTrack.pyx because it changed.
Compiling MACS2/IO/CallPeakUnit.pyx because it changed.
Compiling MACS2/hashtable.pyx because it changed.
Compiling MACS2/Statistics.pyx because it changed.
[ 1/15] Cythonizing MACS2/IO/BedGraph.pyx

Error compiling Cython file:
------------------------------------------------------------
...
            return bpeaks

        thickStart = str(lvl1peakset[0]["start"])
        thickEnd   = str(lvl1peakset[-1]["end"])
        blockNum   = len(lvl1peakset)
        blockSizes = ",".join( map(lambda x:str(x["length"]),lvl1peakset) )
                            ^
------------------------------------------------------------

MACS2/IO/BedGraph.pyx:580:29: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.

Error compiling Cython file:
------------------------------------------------------------
...

        thickStart = str(lvl1peakset[0]["start"])
        thickEnd   = str(lvl1peakset[-1]["end"])
        blockNum   = len(lvl1peakset)
        blockSizes = ",".join( map(lambda x:str(x["length"]),lvl1peakset) )
        blockStarts = ",".join( map(lambda x:str(x["start"]-start),lvl1peakset) )
                             ^
------------------------------------------------------------

MACS2/IO/BedGraph.pyx:581:30: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.

Error compiling Cython file:
------------------------------------------------------------
...
        # add 1bp left and/or right block if necessary
        if int(thickStart) != start:
            # add 1bp left block
            thickStart = str(start)
            blockNum += 1
            blockSizes = "1,"+blockSizes
                            ^
------------------------------------------------------------

MACS2/IO/BedGraph.pyx:588:29: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.

Error compiling Cython file:
------------------------------------------------------------
...
        if int(thickStart) != start:
            # add 1bp left block
            thickStart = str(start)
            blockNum += 1
            blockSizes = "1,"+blockSizes
            blockStarts = "0,"+blockStarts
                             ^
------------------------------------------------------------

MACS2/IO/BedGraph.pyx:589:30: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.

Error compiling Cython file:
------------------------------------------------------------
...
            blockStarts = "0,"+blockStarts
        if int(thickEnd) != end:
            # add 1bp right block
            thickEnd = str(end)
            blockNum += 1
            blockSizes = blockSizes+",1"
                                  ^
------------------------------------------------------------

MACS2/IO/BedGraph.pyx:594:35: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.

Error compiling Cython file:
------------------------------------------------------------
...
                        total_p += 1
                cutoff_lpeaks[ cutoff ] = cutoff_lpeaks.get( cutoff, 0 ) + total_l
                cutoff_npeaks[ cutoff ] = cutoff_npeaks.get( cutoff, 0 ) + total_p

        # write pvalue and total length of predicted peaks
        ret = "pscore\tnpeaks\tlpeaks\tavelpeak\n"
             ^
------------------------------------------------------------

MACS2/IO/BedGraph.pyx:1051:14: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.

Error compiling Cython file:
------------------------------------------------------------
...

        # write pvalue and total length of predicted peaks
        ret = "pscore\tnpeaks\tlpeaks\tavelpeak\n"
        for cutoff in sorted(cutoff_lpeaks.keys(), reverse=True):
            if cutoff_npeaks[ cutoff ] > 0:
                ret += "%.2f\t%d\t%d\t%.2f\n" % ( cutoff, cutoff_npeaks[ cutoff ], cutoff_lpeaks[ cutoff ], cutoff_lpeaks[ cutoff ]/cutoff_npeaks[ cutoff ] )
                   ^
------------------------------------------------------------

MACS2/IO/BedGraph.pyx:1054:20: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.
Traceback (most recent call last):
  File "setup.py", line 115, in <module>
    main()
  File "setup.py", line 111, in main
    ext_modules = cythonize(ext_modules, language_level="2")
  File "/home/kzhou/.conda/envs/py2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1016, in cythonize
    cythonize_one(*args)
  File "/home/kzhou/.conda/envs/py2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1138, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: MACS2/IO/BedGraph.pyx
```

**Comment by taoliu** [comment]
@KR-Chow It seems you were installing MACS2 with Python3. Currently, MACS2 can only be installed and run with Python2.

**Comment by KR-Chow** [comment]
> @KR-Chow It seems you were installing MACS2 with Python3. Currently, MACS2 can only be installed and run with Python2.

Thanks for your reply. I'm sure that I installed MACS2 with command "python2.7 setup.py install" in activated python2.7 environment .

**Comment by taoliu** [comment]
@KR-Chow What's the version for Cython? This error is Python3 specific, so perhaps the Cython you used in your system link to Python3. Also, please try to remove MACS2 from your system and install it through PyPI: `pip install MACS2`.

**Comment by KR-Chow** [comment]
> @KR-Chow What's the version for Cython? This error is Python3 specific, so perhaps the Cython you used in your system link to Python3. Also, please try to remove MACS2 from your system and install it through PyPI: `pip install MACS2`.
The Cython version is 0.28.2. I've successfully installed MACS2 via pip. Thanks!

**Comment by taoliu** [comment]
@KR-Chow Great! I closed the issue.
