### ISSUE TITLE
Bug: Cython dependency in setup.py

### ISSUE THREAD

**Issue by taoliu** [taoliu/MACS#321]
Thanks @taoliu  but it no longer works for me:
```
Collecting MACS2
  Using cached https://files.pythonhosted.org/packages/e9/7d/5e24cf24c048548371fc1892fc9a4261ac92cc31ec7ed99552c73c727e9e/MACS2-2.1.3.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.16_1/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-LCDody/MACS2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-LCDody/MACS2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-LCDody/MACS2/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-LCDody/MACS2/setup.py", line 115, in <module>
        main()
      File "/tmp/pip-install-LCDody/MACS2/setup.py", line 111, in main
        ext_modules = cythonize(ext_modules, language_level="2")
    NameError: global name 'cythonize' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

_Originally posted by @tseemann in https://github.com/taoliu/MACS/issues/295#issuecomment-536170628_

**Comment by taoliu** [comment]
Cython dependency will be removed from setup.py script. Since pypi package will include all C codes translated from Pyx files, cython is not necessary. I will move cythonize call to where 'has_cython' is true.

**Comment by taoliu** [comment]
v2.1.4 was just released. Please let me know if it works or if it does not work @tseemann

**Comment by taoliu** [comment]
A caveat is that if cython exists, the

**Comment by tseemann** [comment]
```
% pip2 install --upgrade --no-binary :none: MACS2
Collecting MACS2
  Downloading https://files.pythonhosted.org/packages/3e/0f/9e34f46341cb0ab5ea67421666ef86c9678fbea1ac9455c716474cd19350/MACS2-2.1.4.tar.gz (1.8MB)
     |################################| 1.8MB 2.7MB/s

  Building wheel for MACS2 (setup.py) ... done
  Created wheel for MACS2: filename=MACS2-2.1.4-cp27-cp27m-linux_x86_64.whl size=5316242 sha256=7fd03a38b5b90f4044a1a1c11ef4cf8f751de081b19a58b07e8a89572d3248d4
  Stored in directory: /home/linuxbrew/.cache/pip/wheels/e8/31/e3/7c609252d075fb5834138808eff99312a07a5fdf0abddd4c2a
Successfully built MACS2
Installing collected packages: MACS2
  Found existing installation: MACS2 2.1.2
    Uninstalling MACS2-2.1.2:
      Successfully uninstalled MACS2-2.1.2
Successfully installed MACS2-2.1.4
```

**Comment by taoliu** [comment]
@tseemann Thanks for the feedback! Issue closed.
