### ISSUE TITLE
"Exception: !!"

### ISSUE THREAD

**Issue by sb-cmd** [taoliu/MACS#352]
I'm having an issue with running callpeak. 
I usually look up the error messages online, but the error message in this case is "!!" and I've had quite a bit of trouble trying to find similar issues.
Any info (even just identifying what the double exclamation mark means) would be really helpful. 
Thank you in advance

-----------------------------------

```
# Command line: callpeak -t ./rh3_k4m1_ps_chip_rmdup.sam -c ./rh3_k4m1_ps_input_rmdup.sam -f SAM -s 40 --broad -g 2.87e9 --broad-cutoff 0.1 -B -n rh3_k4m1_ps
# ARGUMENTS LIST:
# name = rh3_k4m1_ps
# format = SAM
# ChIP-seq file = ['./rh3_k4m1_ps_chip_rmdup.sam']
# control file = ['./rh3_k4m1_ps_input_rmdup.sam']
# effective genome size = 2.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff for narrow/strong regions = 5.00e-02
# qvalue cutoff for broad/weak regions = 1.00e-01
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is on
# Paired-End mode is off
 
INFO  @ Mon, 30 Dec 2019 20:04:28: #1 read tag files... 
INFO  @ Mon, 30 Dec 2019 20:04:28: #1 read treatment tags... 
INFO  @ Mon, 30 Dec 2019 20:04:31:  1000000 
INFO  @ Mon, 30 Dec 2019 20:04:34:  2000000 
INFO  @ Mon, 30 Dec 2019 20:04:37:  3000000 
INFO  @ Mon, 30 Dec 2019 20:04:41:  4000000 
.
.
INFO  @ Mon, 30 Dec 2019 20:07:39:  65000000 
INFO  @ Mon, 30 Dec 2019 20:07:42:  66000000 
Traceback (most recent call last):
  File "/ycga-gpfs/apps/hpc/software/MACS2/2.1.1.20160309-foss-2016b-Python-2.7.13/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.1.20160309', 'macs2')
  File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/ycga-gpfs/apps/hpc/software/MACS2/2.1.1.20160309-foss-2016b-Python-2.7.13/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 617, in <module>
    
  File "/ycga-gpfs/apps/hpc/software/MACS2/2.1.1.20160309-foss-2016b-Python-2.7.13/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 57, in main
    
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 73, in run
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 399, in load_tag_files_options
  File "MACS2/IO/Parser.pyx", line 191, in MACS2.IO.Parser.GenericParser.build_fwtrack (MACS2/IO/Parser.c:4345)
  File "MACS2/IO/Parser.pyx", line 216, in MACS2.IO.Parser.GenericParser.build_fwtrack (MACS2/IO/Parser.c:4254)
  File "MACS2/IO/FixWidthTrack.pyx", line 130, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3440)
  File "MACS2/IO/FixWidthTrack.pyx", line 157, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3307)
Exception: !!
```

**Comment by taoliu** [comment]
@sb-cmd First, could you try to upgrade your MACS2 to a new version? The most recent release of MACS2 under Python2 is v2.1.4 and the release under Python3 is v2.2.6.

Secondly, could you convert SAM to BAM and try again with -f BAM? Sometimes, the SAM file is broken so you will see unexpected errors.

**Comment by sb-cmd** [comment]
I tried both of those suggestions. What ended up working was removing chrUn from all my files through samtools view.
