### ISSUE TITLE
Bug: IndexError: list index out of range 

### ISSUE THREAD

**Issue by MikeWLloyd** [taoliu/MACS#393]
I am encountering the error below. I have not seen this one before, just came up when I started running larger datasets. 

```
INFO  @ Tue, 19 May 2020 18:15:57:
# Command line: callpeak -f BAMPE --nomodel -g mm --keep-dup all --cutoff-analysis --tempdir 20200519T1202285_795-I_GT20_00733_TAAGGCGA-TCTCTCCG_cat/temp -n 795-I_GT20_00733_TAAGGCGA-TCTCTCCG_cat -t 795-I_GT20_00733_TAAGGCGA-TCTCTCCG_cat.sorted.rmDup.rmChrM.rmMulti.filtered.shifted.mm10.bam --outdir 20200519T1202285_795-I_GT20_00733_TAAGGCGA-TCTCTCCG_cat
# ARGUMENTS LIST:
# name = 795-I_GT20_00733_TAAGGCGA-TCTCTCCG_cat
# format = BAMPE
# ChIP-seq file = ['795-I_GT20_00733_TAAGGCGA-TCTCTCCG_cat.sorted.rmDup.rmChrM.rmMulti.filtered.shifted.mm10.bam']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is on

INFO  @ Tue, 19 May 2020 18:15:57: #1 read fragment files...
INFO  @ Tue, 19 May 2020 18:15:57: #1 read treatment fragments...
INFO  @ Tue, 19 May 2020 18:16:01:  1000000
INFO  @ Tue, 19 May 2020 18:16:04:  2000000
INFO  @ Tue, 19 May 2020 18:16:07:  3000000
INFO  @ Tue, 19 May 2020 18:16:11:  4000000
INFO  @ Tue, 19 May 2020 18:16:14:  5000000
INFO  @ Tue, 19 May 2020 18:16:17:  6000000
INFO  @ Tue, 19 May 2020 18:16:21:  7000000
INFO  @ Tue, 19 May 2020 18:16:24:  8000000
INFO  @ Tue, 19 May 2020 18:16:28:  9000000
INFO  @ Tue, 19 May 2020 18:16:31:  10000000
INFO  @ Tue, 19 May 2020 18:16:34:  11000000
INFO  @ Tue, 19 May 2020 18:16:38:  12000000
INFO  @ Tue, 19 May 2020 18:16:41:  13000000
INFO  @ Tue, 19 May 2020 18:16:44:  14000000
INFO  @ Tue, 19 May 2020 18:16:47:  15000000
INFO  @ Tue, 19 May 2020 18:16:51:  16000000
INFO  @ Tue, 19 May 2020 18:16:54:  17000000
INFO  @ Tue, 19 May 2020 18:16:57:  18000000
INFO  @ Tue, 19 May 2020 18:17:00:  19000000
INFO  @ Tue, 19 May 2020 18:17:04:  20000000
INFO  @ Tue, 19 May 2020 18:17:07:  21000000
INFO  @ Tue, 19 May 2020 18:17:10:  22000000
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 653, in <module>
    main()
  File "/usr/local/bin/macs2", line 51, in main
    run( args )
  File "/usr/local/lib/python3.8/site-packages/MACS2/callpeak_cmd.py", line 64, in run
    if options.PE_MODE: (treat, control) = load_frag_files_options (options)
  File "/usr/local/lib/python3.8/site-packages/MACS2/callpeak_cmd.py", line 350, in load_frag_files_options
    treat = tp.build_petrack()
  File "MACS2/IO/Parser.pyx", line 1267, in MACS2.IO.Parser.BAMPEParser.build_petrack
  File "MACS2/IO/Parser.pyx", line 1300, in MACS2.IO.Parser.BAMPEParser.build_petrack
IndexError: list index out of range
```

**Comment by MikeWLloyd** [comment]
User error on bam format

**Comment by taoliu** [comment]
Thanks for the update! I think I need to let MACS2 output a more informative error message.
