### ISSUE TITLE
Bug: error when running bdgopt in python3 but not in python2

### ISSUE THREAD

**Issue by olechnwin** [taoliu/MACS#396]
Hi,
I got the following error when running `macs2 bdgopt` in macs2 version 2.2.6 but no error in macs2 version 2.1.4. which makes me think this is due to python2 versus python3.

```
macs2 bdgopt -i 250K_Rb_1k_bg.pileup.bdg -m multiply -p .2090 -o 250K_Rb_1k_bg_norm.bdg
INFO  @ Tue, 19 May 2020 15:25:33: Read and build bedGraph...
INFO  @ Tue, 19 May 2020 15:25:37: Modify bedGraph...
INFO  @ Tue, 19 May 2020 15:25:37: Write bedGraph of modified scores...
Traceback (most recent call last):
  File "/opt/miniconda3/envs/macs2_env/bin/macs2", line 652, in <module>
    main()
  File "/opt/miniconda3/envs/macs2_env/bin/macs2", line 73, in main
    run( args )
  File "/opt/miniconda3/envs/macs2_env/lib/python3.7/site-packages/MACS2/bdgopt_cmd.py", line 68, in run
    btrack.write_bedGraph(ofhd,name="%s_modified_scores" % (options.method.upper()),description="Scores calculated by %s" % (options.method.upper()))
  File "MACS2/IO/BedGraph.pyx", line 247, in MACS2.IO.BedGraph.bedGraphTrackI.write_bedGraph
TypeError: a bytes-like object is required, not 'str'
```
I'm attaching the input file to re-create the error. The input file was generated following the subcommands tutorial of macs2.

[250K_Rb_1k_bg.pileup.bdg.gz](https://github.com/taoliu/MACS/files/4684306/250K_Rb_1k_bg.pileup.bdg.gz)

Thank you!

**Comment by olechnwin** [comment]
Sorry! I should've checked the issues before posting this. The error I mentioned above is already fixed in macs2-2.2.7.
