### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by ghost** [taoliu/MACS#65]
With the following command

```
macs2 callpeak --broad -t results/sicer_input/regular_hg19_1_200_150_0.74_600_.01.bed  -c results/sicer_input/control_hg19_1_200_150_0.74_600_.01.bed --nomodel --extsize 146 --name broad_peaks_extsize_146
```

I got this error message (some output shown):

```
INFO  @ Mon, 19 Jan 2015 11:11:43:  101000000
INFO  @ Mon, 19 Jan 2015 11:11:44:  102000000
^QINFO  @ Mon, 19 Jan 2015 11:11:54: #1 tag size is determined as 51 bps
INFO  @ Mon, 19 Jan 2015 11:11:54: #1 tag size = 51
INFO  @ Mon, 19 Jan 2015 11:11:54: #1  total tags in treatment: 83049643
INFO  @ Mon, 19 Jan 2015 11:11:54: #1 user defined the maximum tags...
INFO  @ Mon, 19 Jan 2015 11:11:54: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s)
INFO  @ Mon, 19 Jan 2015 11:12:07: #1  tags after filtering in treatment: 73842618
INFO  @ Mon, 19 Jan 2015 11:12:07: #1  Redundant rate of treatment: 0.11
INFO  @ Mon, 19 Jan 2015 11:12:07: #1  total tags in control: 102171050
INFO  @ Mon, 19 Jan 2015 11:12:07: #1 user defined the maximum tags...
INFO  @ Mon, 19 Jan 2015 11:12:07: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s)
INFO  @ Mon, 19 Jan 2015 11:12:25: #1  tags after filtering in control: 99296421
INFO  @ Mon, 19 Jan 2015 11:12:25: #1  Redundant rate of control: 0.03
INFO  @ Mon, 19 Jan 2015 11:12:25: #1 finished!
INFO  @ Mon, 19 Jan 2015 11:12:25: #2 Build Peak Model...
INFO  @ Mon, 19 Jan 2015 11:12:25: #2 Skipped...
INFO  @ Mon, 19 Jan 2015 11:12:25: #2 Use 146 as fragment length
INFO  @ Mon, 19 Jan 2015 11:12:25: #3 Call peaks...
INFO  @ Mon, 19 Jan 2015 11:12:25: #3 Call broad peaks with given level1 -log10qvalue cutoff and level2: 1.301030, 1.000000...
INFO  @ Mon, 19 Jan 2015 11:12:25: #3 Pre-compute pvalue-qvalue table...
INFO  @ Mon, 19 Jan 2015 11:32:42: #3 Call peaks for each chromosome...
Traceback (most recent call last):
  File "/Users/endrebakkenstovner/anaconda/bin/macs2", line 559, in <module>
    main()
  File "/Users/endrebakkenstovner/anaconda/bin/macs2", line 56, in main
    run( args )
  File "/Users/endrebakkenstovner/anaconda/lib/python2.7/site-packages/MACS2/callpeak.py", line 261, in run
    peakdetect.call_peaks()
  File "cPeakDetect.pyx", line 105, in MACS2.cPeakDetect.PeakDetect.call_peaks (MACS2/cPeakDetect.c:1696)
  File "cPeakDetect.pyx", line 256, in MACS2.cPeakDetect.PeakDetect.__call_peaks_w_control (MACS2/cPeakDetect.c:3276)
  File "cCallPeakUnit.pyx", line 964, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.call_broadpeaks (MACS2/IO/cCallPeakUnit.c:13516)
  File "cCallPeakUnit.pyx", line 1047, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.call_broadpeaks (MACS2/IO/cCallPeakUnit.c:13210)
  File "cCallPeakUnit.pyx", line 1238, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.__add_broadpeak (MACS2/IO/cCallPeakUnit.c:15428)
  File "cPeakIO.pyx", line 799, in MACS2.IO.cPeakIO.BroadPeakIO.add (MACS2/IO/cPeakIO.c:13956)
OverflowError: Python int too large to convert to C long
```

The offending code is in [this line](https://github.com/taoliu/MACS/blob/master/MACS2/IO/cPeakIO.pyx#L799)

```
def add (self, char * chromosome, long start, long end, long score = 0,
str thickStart=".", str thickEnd=".",
long blockNum=0, str blockSizes=".",
str blockStarts=".", float pileup = 0,
float pscore = 0, float fold_change = 0,
float qscore = 0, str name = "NA" ):
```

I've never used cython before, but is the fix just to make the long a longlong?

Ps. will rerun the same command with debug-level verbosity and post messages.

**Comment by endrebak** [comment]
Also trying `--broad-cutoff 0.1` since I'm analyzing H3K27 to see whether that is related to the bug.

**Comment by endrebak** [comment]
Same error:

```
INFO  @ Mon, 19 Jan 2015 12:10:25:  101000000
INFO  @ Mon, 19 Jan 2015 12:10:27:  102000000
INFO  @ Mon, 19 Jan 2015 12:10:37: #1 tag size is determined as 51 bps
INFO  @ Mon, 19 Jan 2015 12:10:37: #1 tag size = 51
INFO  @ Mon, 19 Jan 2015 12:10:37: #1  total tags in treatment: 83049643
INFO  @ Mon, 19 Jan 2015 12:10:37: #1 user defined the maximum tags...
INFO  @ Mon, 19 Jan 2015 12:10:37: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s)
INFO  @ Mon, 19 Jan 2015 12:10:51: #1  tags after filtering in treatment: 73842618
INFO  @ Mon, 19 Jan 2015 12:10:51: #1  Redundant rate of treatment: 0.11
INFO  @ Mon, 19 Jan 2015 12:10:51: #1  total tags in control: 102171050
INFO  @ Mon, 19 Jan 2015 12:10:51: #1 user defined the maximum tags...
INFO  @ Mon, 19 Jan 2015 12:10:51: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s)
INFO  @ Mon, 19 Jan 2015 12:11:08: #1  tags after filtering in control: 99296421
INFO  @ Mon, 19 Jan 2015 12:11:08: #1  Redundant rate of control: 0.03
INFO  @ Mon, 19 Jan 2015 12:11:08: #1 finished!
INFO  @ Mon, 19 Jan 2015 12:11:08: #2 Build Peak Model...
INFO  @ Mon, 19 Jan 2015 12:11:08: #2 Skipped...
INFO  @ Mon, 19 Jan 2015 12:11:08: #2 Use 146 as fragment length
INFO  @ Mon, 19 Jan 2015 12:11:08: #3 Call peaks...
INFO  @ Mon, 19 Jan 2015 12:11:08: #3 Call broad peaks with given level1 -log10qvalue cutoff and level2: 1.301030, 1.000000...
INFO  @ Mon, 19 Jan 2015 12:11:08: #3 Pre-compute pvalue-qvalue table...
DEBUG @ Mon, 19 Jan 2015 12:11:08: Start to calculate pvalue stat...
DEBUG @ Mon, 19 Jan 2015 12:31:34: make pvalue_stat cost 0.00000 seconds
DEBUG @ Mon, 19 Jan 2015 12:31:34: calculate pvalue/access hash for 633648189 times
DEBUG @ Mon, 19 Jan 2015 12:31:34: access pq hash for 633799356 times
INFO  @ Mon, 19 Jan 2015 12:31:34: #3 Call peaks for each chromosome...
Traceback (most recent call last):
  File "/Users/endrebakkenstovner/anaconda/bin/macs2", line 559, in <module>
    main()
  File "/Users/endrebakkenstovner/anaconda/bin/macs2", line 56, in main
    run( args )
  File "/Users/endrebakkenstovner/anaconda/lib/python2.7/site-packages/MACS2/callpeak.py", line 261, in run
    peakdetect.call_peaks()
  File "cPeakDetect.pyx", line 105, in MACS2.cPeakDetect.PeakDetect.call_peaks (MACS2/cPeakDetect.c:1696)
  File "cPeakDetect.pyx", line 256, in MACS2.cPeakDetect.PeakDetect.__call_peaks_w_control (MACS2/cPeakDetect.c:3276)
  File "cCallPeakUnit.pyx", line 964, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.call_broadpeaks (MACS2/IO/cCallPeakUnit.c:13516)
  File "cCallPeakUnit.pyx", line 1047, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.call_broadpeaks (MACS2/IO/cCallPeakUnit.c:13210)
  File "cCallPeakUnit.pyx", line 1238, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.__add_broadpeak (MACS2/IO/cCallPeakUnit.c:15428)
  File "cPeakIO.pyx", line 799, in MACS2.IO.cPeakIO.BroadPeakIO.add (MACS2/IO/cPeakIO.c:13956)
OverflowError: Python int too large to convert to C long
```

Command used:

```
macs2 callpeak --broad -t results/sicer_input/regular_hg19_1_200_150_0.74_600_.01.bed  -c results/sicer_input/control_hg19_1_200_150_0.74_600_.01.bed --nomodel --extsize 146 --name broad_peaks_extsize_146 --broad-cutoff 0.1 --verbose 3
```

**Comment by endrebak** [comment]
Version info:
`macs2 2.1.0.20140616`

**Comment by endrebak** [comment]
Will try to bypass this by running MACS2 per chromosome.

**Comment by endrebak** [comment]
Doing the analysis chromosome-wise did not work (I did not have much hope for it either, as it would only reduce the size by a factor of ~20).

```
DEBUG @ Tue, 20 Jan 2015 07:13:31: access pq hash for 52293252 times
INFO  @ Tue, 20 Jan 2015 07:13:31: #3 Call peaks for each chromosome...
Traceback (most recent call last):
  File "/Users/endrebakkenstovner/anaconda/bin/macs2", line 559, in <module>
    main()
  File "/Users/endrebakkenstovner/anaconda/bin/macs2", line 56, in main
    run( args )
  File "/Users/endrebakkenstovner/anaconda/lib/python2.7/site-packages/MACS2/callpeak.py", line 261, in run
    peakdetect.call_peaks()
  File "cPeakDetect.pyx", line 105, in MACS2.cPeakDetect.PeakDetect.call_peaks (MACS2/cPeakDetect.c:1696)
  File "cPeakDetect.pyx", line 256, in MACS2.cPeakDetect.PeakDetect.__call_peaks_w_control (MACS2/cPeakDetect.c:3276)
  File "cCallPeakUnit.pyx", line 964, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.call_broadpeaks (MACS2/IO/cCallPeakUnit.c:13516)
  File "cCallPeakUnit.pyx", line 1047, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.call_broadpeaks (MACS2/IO/cCallPeakUnit.c:13210)
  File "cCallPeakUnit.pyx", line 1238, in MACS2.IO.cCallPeakUnit.CallerFromAlignments.__add_broadpeak (MACS2/IO/cCallPeakUnit.c:15428)
  File "cPeakIO.pyx", line 799, in MACS2.IO.cPeakIO.BroadPeakIO.add (MACS2/IO/cPeakIO.c:13956)
OverflowError: Python int too large to convert to C long
```

**Comment by endrebak** [comment]
This worked on Ubuntu.

I'm guessing this is a OSX clang vs. GCC issue, but I do not know anything about Cython.

`gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)`

```
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

**Comment by chebyshev** [comment]
endrebak,
I have encountered the same error even with gcc 4.8.2-16 on RHEL7.
So far, I have found that this error can be seen when broad option is used and it's not always reproducible.

**Comment by Elisaby** [comment]
endrebak,
I have encountered the same error running MACS2 for ChIP seq bam files. I haven't specified the broad option, so I don't think that is the problem. Have you solved this question?

**Comment by endrebak** [comment]
I haven't looked more into it. Perhaps you should send an e-mail to the developer if he isn't watching the issues page.

**Comment by endrebak** [comment]
This should probably not happen when using Python3 since all Python3 ints are unlimited precision.

**Comment by taoliu** [comment]
Closing years old issues. Please reopen if you are still interested.
