### ISSUE TITLE
IndexError out of bounds

### ISSUE THREAD

**Issue by masaf2** [taoliu/MACS#78]
Hello,

I have a problem while trying to run macs2 callpeak (see error message below). Here's my command line :

macs2 callpeak -t SRR574758.sorted.bam SRR574759.sorted.bam -f BAM -g mm --trackline -B --SPMR --call-summits -n peakcalling --outdir MACS

I've tried to uninstall MACS2 and re-install from source code (macs2 2.1.0.20150420) and update NumPy but I always get the same error saying the index 650321 is out of bounds for axis 0 with size 650321...

Could you help me to resolve this issue please ?
Thanks a lot !
MSF

Here's the error message I get :

Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 5, in <module>
    pkg_resources.run_script('MACS2==2.1.0.20150420', 'macs2')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.0.20150420-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 614, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.0.20150420-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main
    
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 70, in run
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 400, in load_tag_files_options
  File "MACS2/IO/Parser.pyx", line 888, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12930)
  File "MACS2/IO/Parser.pyx", line 892, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12878)
  File "MACS2/IO/Parser.pyx", line 961, in MACS2.IO.Parser.BAMParser.__append_fwtrack_wo_pysam (MACS2/IO/Parser.c:14106)
  File "MACS2/IO/FixWidthTrack.pyx", line 130, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3181)
  File "MACS2/IO/FixWidthTrack.pyx", line 149, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3040)
IndexError: index 650321 is out of bounds for axis 0 with size 650321

**Comment by bzvew** [comment]
I also have similar problem:

macs2 callpeak -t msh2.bam ddb1.bam  -f BAM -g hs -n out -B -q 0.01
INFO  @ Tue, 19 May 2015 09:52:32: 
# Command line: callpeak -t msh2.bam ddb1.bam -f BAM -g hs -n out -B -q 0.01
# ARGUMENTS LIST:
# name = out
# format = BAM
# ChIP-seq file = ['msh2.bam', 'ddb1.bam']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
 
INFO  @ Tue, 19 May 2015 09:52:32: #1 read tag files... 
INFO  @ Tue, 19 May 2015 09:52:32: #1 read treatment tags... 
INFO  @ Tue, 19 May 2015 09:52:40:  1000000 
INFO  @ Tue, 19 May 2015 09:52:48:  2000000 
INFO  @ Tue, 19 May 2015 09:52:56:  3000000 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/macs2", line 614, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/macs2", line 56, in main
    run( args )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 70, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 400, in load_tag_files_options
    treat = tp.append_fwtrack( treat )
  File "MACS2/IO/Parser.pyx", line 888, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12930)
  File "MACS2/IO/Parser.pyx", line 892, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12878)
  File "MACS2/IO/Parser.pyx", line 961, in MACS2.IO.Parser.BAMParser.__append_fwtrack_wo_pysam (MACS2/IO/Parser.c:14106)
  File "MACS2/IO/FixWidthTrack.pyx", line 130, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3181)
  File "MACS2/IO/FixWidthTrack.pyx", line 149, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3040)
IndexError: index out of bounds

**Comment by bzvew** [comment]
I find if I input one bam for each run, the issue will be solved.

**Comment by masaf2** [comment]
Thanks for your reply ! I just tried and it worked well but what if I have more than one biological replicate ? I thought MACS2 was able to handle that case... I worked with MACS2 last year and it used to work with at least two replicates...

**Comment by ghuls** [comment]
I have the same problem:

```
$ macs2 callpeak -g mm -n /tmp/dana_smaller100_dm6_test --nomodel -t 14.BigWig_dm6/dana_May_clean_sup5.lift.dm6.mapped_smaller100bp.bg 14.BigWig_dm6/dana_Jun_clean_sup5.lift.dm6.mapped_smaller100bp.bg
INFO  @ Thu, 21 May 2015 18:17:34: 
# Command line: callpeak -g mm -n /tmp/dana_smaller100_dm6_test --nomodel -t 14.BigWig_dm6/dana_May_clean_sup5.lift.dm6.mapped_smaller100bp.bg 14.BigWig_dm6/dana_Jun_clean_sup5.lift.dm6.mapped_smaller100bp.bg
# ARGUMENTS LIST:
# name = /tmp/dana_smaller100_dm6_test
# format = AUTO
# ChIP-seq file = ['14.BigWig_dm6/dana_May_clean_sup5.lift.dm6.mapped_smaller100bp.bg', '14.BigWig_dm6/dana_Jun_clean_sup5.lift.dm6.mapped_smaller100bp.bg']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
 
INFO  @ Thu, 21 May 2015 18:17:34: #1 read tag files... 
INFO  @ Thu, 21 May 2015 18:17:34: #1 read treatment tags... 
INFO  @ Thu, 21 May 2015 18:17:34: Detected format is: BED 
INFO  @ Thu, 21 May 2015 18:17:36:  1000000 
INFO  @ Thu, 21 May 2015 18:17:39:  2000000 
INFO  @ Thu, 21 May 2015 18:17:41:  3000000 
INFO  @ Thu, 21 May 2015 18:17:44:  4000000 
INFO  @ Thu, 21 May 2015 18:17:47:  5000000 
INFO  @ Thu, 21 May 2015 18:17:49: Detected format is: BED 
Traceback (most recent call last):
  File "/software/macs/macs-git-2015-04-24-virtenv/bin/macs2", line 614, in <module>
    main()
  File "/software/macs/macs-git-2015-04-24-virtenv/bin/macs2", line 56, in main
    run( args )
  File "/software/macs/macs-git-2015-04-24-virtenv/local/lib/python2.7/site-packages/MACS2-2.1.0.20150420-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 70, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/software/macs/macs-git-2015-04-24-virtenv/local/lib/python2.7/site-packages/MACS2-2.1.0.20150420-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 400, in load_tag_files_options
    treat = tp.append_fwtrack( treat )
  File "Parser.pyx", line 233, in MACS2.IO.Parser.GenericParser.append_fwtrack (MACS2/IO/Parser.c:4493)
  File "Parser.pyx", line 250, in MACS2.IO.Parser.GenericParser.append_fwtrack (MACS2/IO/Parser.c:4395)
  File "FixWidthTrack.pyx", line 130, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3220)
  File "FixWidthTrack.pyx", line 149, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3084)
IndexError: index out of bounds

```

**Comment by akshayaramesh** [comment]
Did any of you have any luck resolving this? I have the same issue!

**Comment by akshayaramesh** [comment]
I think it might be an issue with the nee version of the program. I ran the same files on an older version and it finished without any errors!

**Comment by taoliu** [comment]
I suspect it's related to the feature to accept multiple input files from -t or -c. We are working on it.

**Comment by taoliu** [comment]
Fixed in b330726fef0d10858dd2db13ab243e02f97828f8

**Comment by zifeng9527** [comment]
I have updated it, but it seems the issue still be there. 

====================================
zifeng9527@ubuntu:~/Downloads/HB ChIP-seq$ macs2 callpeak -t K562ATF1R1.bam K562ATF1R2.bam -c K562INPUTR1.bam K562INPUTR2.bam --outdir K562ATF1R12peak -f BAM -g hs -n K562ATF1R12PEAK -B -q 0.01
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:1224: UserWarning: /home/zifeng9527/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
INFO  @ Thu, 04 Jun 2015 12:15:38: 
# Command line: callpeak -t K562ATF1R1.bam K562ATF1R2.bam -c K562INPUTR1.bam K562INPUTR2.bam --outdir K562ATF1R12peak -f BAM -g hs -n K562ATF1R12PEAK -B -q 0.01
# ARGUMENTS LIST:
# name = K562ATF1R12PEAK
# format = BAM
# ChIP-seq file = ['K562ATF1R1.bam', 'K562ATF1R2.bam']
# control file = ['K562INPUTR1.bam', 'K562INPUTR2.bam']
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
 
INFO  @ Thu, 04 Jun 2015 12:15:38: #1 read tag files... 
INFO  @ Thu, 04 Jun 2015 12:15:38: #1 read treatment tags... 
INFO  @ Thu, 04 Jun 2015 12:15:40:  1000000 
INFO  @ Thu, 04 Jun 2015 12:15:42:  2000000 
INFO  @ Thu, 04 Jun 2015 12:15:44:  3000000 
INFO  @ Thu, 04 Jun 2015 12:15:45:  4000000 
INFO  @ Thu, 04 Jun 2015 12:15:47:  5000000 
INFO  @ Thu, 04 Jun 2015 12:15:49:  6000000 
INFO  @ Thu, 04 Jun 2015 12:15:51:  7000000 
INFO  @ Thu, 04 Jun 2015 12:15:53:  8000000 
INFO  @ Thu, 04 Jun 2015 12:15:55:  9000000 
INFO  @ Thu, 04 Jun 2015 12:15:57:  10000000 
INFO  @ Thu, 04 Jun 2015 12:15:58:  11000000 
INFO  @ Thu, 04 Jun 2015 12:16:00:  12000000 
INFO  @ Thu, 04 Jun 2015 12:16:02:  13000000 
INFO  @ Thu, 04 Jun 2015 12:16:04:  14000000 
INFO  @ Thu, 04 Jun 2015 12:16:06:  15000000 
INFO  @ Thu, 04 Jun 2015 12:16:08:  16000000 
INFO  @ Thu, 04 Jun 2015 12:16:09:  17000000 
INFO  @ Thu, 04 Jun 2015 12:16:11:  18000000 
INFO  @ Thu, 04 Jun 2015 12:16:13:  19000000 
INFO  @ Thu, 04 Jun 2015 12:16:15:  20000000 
INFO  @ Thu, 04 Jun 2015 12:16:17:  21000000 
INFO  @ Thu, 04 Jun 2015 12:16:19:  22000000 
INFO  @ Thu, 04 Jun 2015 12:16:21:  23000000 
INFO  @ Thu, 04 Jun 2015 12:16:22:  24000000 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.0.20150603', 'macs2')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 698, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1623, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 611, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 53, in main
    
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 70, in run
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 400, in load_tag_files_options
  File "MACS2/IO/Parser.pyx", line 888, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12930)
  File "MACS2/IO/Parser.pyx", line 892, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12878)
  File "MACS2/IO/Parser.pyx", line 961, in MACS2.IO.Parser.BAMParser.__append_fwtrack_wo_pysam (MACS2/IO/Parser.c:14106)
  File "MACS2/IO/FixWidthTrack.pyx", line 130, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3181)
  File "MACS2/IO/FixWidthTrack.pyx", line 149, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3040)
IndexError: index 1301023 is out of bounds for axis 0 with size 1301023
zifeng9527@ubuntu:~/Downloads/HB ChIP-seq$ 

=================
Btw, I am a fresh bird for Linux.

I just replaced the updated code in each file according https://github.com/taoliu/MACS/commit/b330726fef0d10858dd2db13ab243e02f97828f8

Then re-install the program by using the command  $ python setup.py install

I check the version, it seems well 
zifeng9527@ubuntu:~/Downloads/HB ChIP-seq$ macs2 --version
macs2 2.1.0.20150603



Thank you.

**Comment by taoliu** [comment]
@zifeng9527

The reason is that the C codes haven't been updated. We only provide 'pyx' files on github so in reality, you need to use 'python setup_w_cython.py install' command to install. This command will first translate pyx into C code using Cython ( you need to install Cython first) then compile and install. Whereas 'setup.py' will not do the translation.  On the other hand, the package, which hasn't been updated yet, on PYPI site contains all C codes instead of pyx files. I am still looking for other issues that need to be fixed before I upload a new release to PYPI.

Tao

**Comment by ghuls** [comment]
I installed the last version from git.
And now it works fine.

**Comment by taoliu** [comment]
@ghuls Thanks for the feedback!

Now, the ticket is closed. Open it if anyone still finds the same issue.

**Comment by rspreafico** [comment]
+ macs2 callpeak -t BC6.bam -f BAMPE -n BC6 -g mm -p 1e-5 --keep-dup 1 --call-summits --nolambda --slocal 10000 --nomodel --outdir ../../08_macs/BC6
INFO  @ Sat, 01 Aug 2015 16:01:12:
# Command line: callpeak -t BC6.bam -f BAMPE -n BC6 -g mm -p 1e-5 --keep-dup 1 --call-summits --nolambda --slocal 10000 --nomodel --outdir ../../08_macs/BC6
# ARGUMENTS LIST:
# name = BC6
# format = BAMPE
# ChIP-seq file = ['BC6.bam']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# pvalue cutoff = 1.00e-05
# qvalue will not be calculated and reported as -1 in the final output.
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Searching for subpeak summits is on

INFO  @ Sat, 01 Aug 2015 16:01:12: #1 read fragment files...
INFO  @ Sat, 01 Aug 2015 16:01:12: #1 read treatment fragments...
INFO  @ Sat, 01 Aug 2015 16:01:34:  1000000
INFO  @ Sat, 01 Aug 2015 16:01:54:  2000000
INFO  @ Sat, 01 Aug 2015 16:02:14:  3000000
INFO  @ Sat, 01 Aug 2015 16:02:37:  4000000
INFO  @ Sat, 01 Aug 2015 16:02:58:  5000000
INFO  @ Sat, 01 Aug 2015 16:03:19:  6000000
INFO  @ Sat, 01 Aug 2015 16:03:41:  7000000
INFO  @ Sat, 01 Aug 2015 16:03:57: #1 mean fragment size is determined as 177 bp from treatment
INFO  @ Sat, 01 Aug 2015 16:03:57: #1 fragment size = 177
INFO  @ Sat, 01 Aug 2015 16:03:57: #1  total fragments in treatment: 7610158
INFO  @ Sat, 01 Aug 2015 16:03:57: #1 user defined the maximum
INFO  @ Sat, 01 Aug 2015 16:03:57: #1 filter out redundant fragments by allowing at most 1 identical fragment(s)
Traceback (most recent call last):
  File "/opt/anaconda/bin/macs2", line 614, in <module>
    main()
  File "/opt/anaconda/bin/macs2", line 56, in main
    run( args )
  File "/opt/anaconda/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 100, in run
    treat.separate_dups(treatment_max_dup_tags) # changed 5-29
  File "MACS2/IO/PairedEndTrack.pyx", line 311, in MACS2.IO.PairedEndTrack.PETrackI.separate_dups (MACS2/IO/PairedEndTrack.c:5342)
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by taoliu** [comment]
@rspreafico  Could you share me the 'samtools flagstat' information about your BC6.bam file? Never experience such problem. But if you could down sample your bam file and send me a smaller file to reproduce the problem, that would be extremely helpful.

**Comment by rspreafico** [comment]
Hi Tao,

thanks! This is samtools flagstat's output:

15220406 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
15220406 + 0 mapped (100.00%:-nan%)
15220406 + 0 paired in sequencing
7610203 + 0 read1
7610203 + 0 read2
15220406 + 0 properly paired (100.00%:-nan%)
15220406 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:-nan%)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

This is the whole BC6.bam file (about 700 Mb), I will keep the link live for 24 hours:
https://dl.dropboxusercontent.com/u/8992918/BC6.bam

Thank you,

Roberto

**Comment by rspreafico** [comment]
If it helps, just found that changing from --keep-dup 1 to -keep-dup all let MACS2 complete without errors. Since this BAM file is already dedupped with Picard that is fine with me.

**Comment by chxu02** [comment]
just upgraded from MACS2-2.1.0.20140616 to MACS2-2.1.0.20150731 using pip.
same problem occurred which never happened to me when I used 20140616.

MACS2 callpeak -t H3K27ac+Bio_Veh_R1.bam -n H3K27ac+Bio_Veh_R1 -f BAMPE -g dm --keep-dup auto
INFO  @ Tue, 25 Aug 2015 15:33:32: 
# Command line: callpeak -t H3K27ac+Bio_Veh_R1.bam -n H3K27ac+Bio_Veh_R1 -f BAMPE -g dm --keep-dup auto
# ARGUMENTS LIST:
# name = H3K27ac+Bio_Veh_R1
# format = BAMPE
# ChIP-seq file = ['H3K27ac+Bio_Veh_R1.bam']
# control file = None
# effective genome size = 1.20e+08
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
 
INFO  @ Tue, 25 Aug 2015 15:33:32: #1 read fragment files... 
INFO  @ Tue, 25 Aug 2015 15:33:32: #1 read treatment fragments... 
INFO  @ Tue, 25 Aug 2015 15:33:47:  1000000 
INFO  @ Tue, 25 Aug 2015 15:34:01:  2000000 
INFO  @ Tue, 25 Aug 2015 15:34:15:  3000000 
INFO  @ Tue, 25 Aug 2015 15:34:30:  4000000 
INFO  @ Tue, 25 Aug 2015 15:34:45:  5000000 
INFO  @ Tue, 25 Aug 2015 15:35:00:  6000000 
INFO  @ Tue, 25 Aug 2015 15:35:04: #1 mean fragment size is determined as 189 bp from treatment 
INFO  @ Tue, 25 Aug 2015 15:35:04: #1 fragment size = 189 
INFO  @ Tue, 25 Aug 2015 15:35:04: #1  total fragments in treatment: 6005304 
INFO  @ Tue, 25 Aug 2015 15:35:04: #1 calculate max duplicate fragments in single position based on binomial distribution... 
INFO  @ Tue, 25 Aug 2015 15:35:04: #1  max_dup_tags based on binomial = 3 
INFO  @ Tue, 25 Aug 2015 15:35:04: #1 filter out redundant fragments by allowing at most 3 identical fragment(s) 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/MACS2", line 614, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/MACS2", line 56, in main
    run( args )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 100, in run
    treat.separate_dups(treatment_max_dup_tags) # changed 5-29
  File "MACS2/IO/PairedEndTrack.pyx", line 311, in MACS2.IO.PairedEndTrack.PETrackI.separate_dups (MACS2/IO/PairedEndTrack.c:5342)
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by taoliu** [comment]
Could you describe how you upgraded MACS2? The path "/Library/Frameworks/Python.framework/Versions/2.7/bin/MACS2” looks suspicious to me. If you install through pip, the path should be ‘/usr/local/bin/'

Tao

**Comment by chxu02** [comment]
I just typed: sudo pip install -U MACS2

**Comment by chxu02** [comment]
BTW, the running was OK if I chose not to do deduplication (--keep-dup all)

**Comment by sandertan** [comment]
Hi, I'm also experiencing this issue with a paired-end sequenced sample. Running macs2 2.1.0.20150731. Just like the previous posters, the issue does not arise when I specify: --keep-dup all. Something that might cause the problem, is that the BAM-file already has it's duplicates removed. So it's easy to work around the problem. 

The test sample:
SRR891269.sra from GSM1155958 

The error:
macs2 callpeak -B -p 1e-5 -g hs -f BAMPE -t SRR891269.bam -n SRR891269_test3INFO  @ Fri, 25 Sep 2015 11:05:15: 
 Command line: callpeak -B -p 1e-5 -g hs -f BAMPE -t SRR891269.bam -n SRR891269_test3
 ARGUMENTS LIST:
 name = SRR891269_test3
 format = BAMPE
 ChIP-seq file = ['SRR891269.bam']
 control file = None
 effective genome size = 2.70e+09
 band width = 300
 model fold = [5, 50]
 pvalue cutoff = 1.00e-05
 qvalue will not be calculated and reported as -1 in the final output.
 Larger dataset will be scaled towards smaller dataset.
 Range for calculating regional lambda is: 10000 bps
 Broad region calling is off

NFO  @ Fri, 25 Sep 2015 10:48:12: #1 read tag files... 
INFO  @ Fri, 25 Sep 2015 10:48:12: #1 read treatment tags... 
INFO  @ Fri, 25 Sep 2015 10:48:12: Detected format is: BAM 
INFO  @ Fri, 25 Sep 2015 10:48:12: * Input file is gzipped. 
INFO  @ Fri, 25 Sep 2015 10:48:14:  1000000
....
INFO  @ Fri, 25 Sep 2015 11:08:43:  35000000 
INFO  @ Fri, 25 Sep 2015 11:09:41: #1 mean fragment size is determined as 209 bp from treatment 
INFO  @ Fri, 25 Sep 2015 11:09:41: #1 fragment size = 209 
INFO  @ Fri, 25 Sep 2015 11:09:41: #1  total fragments in treatment: 35982063 
INFO  @ Fri, 25 Sep 2015 11:09:41: #1 user defined the maximum fragments... 
INFO  @ Fri, 25 Sep 2015 11:09:41: #1 filter out redundant fragments by allowing at most 1 identical fragment(s) 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 614, in <module>
    main()
  File "/usr/local/bin/macs2", line 56, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/callpeak_cmd.py", line 100, in run
    treat.separate_dups(treatment_max_dup_tags) # changed 5-29
  File "MACS2/IO/PairedEndTrack.pyx", line 311, in MACS2.IO.PairedEndTrack.PETrackI.separate_dups (MACS2/IO/PairedEndTrack.c:5342)
IndexError: index out of bounds

**Comment by joshua-theisen** [comment]
I get the same IndexError. I am running on a HPC cluster with the following modules loaded:
```
$ module list
Currently Loaded Modules:
  1) gcc/6.2.0   2) bzip2/1.0.6   3) python/2.7.13   4) macs2/2.1.0
```

Here is my code and the error:
```
$ macs2 callpeak \
>     -t  <path>/SRR11305450.sort.bam \
>         <path>/align/SRR11305451.sort.bam \
>     -f BAM \
>     -g mm \
>     -n WF_Gli3 \
>     -B \
>     -q 0.05 \
>     --SPMR \
>     --outdir /gpfs/data/moskowitz-lab/josh/frem1/callpeak/
INFO  @ Fri, 10 Jun 2022 07:41:06:
# Command line: callpeak -t <path>/SRR11305450.sort.bam <path>/SRR11305451.sort.bam -f BAM -g mm -n WF_Gli3 -B -q 0.05 --SPMR --outdir /gpfs/data/moskowitz-lab/josh/frem1/callpeak/
# ARGUMENTS LIST:
# name = WF_Gli3
# format = BAM
# ChIP-seq file = ['<path>/SRR11305450.sort.bam', '<path>/SRR11305451.sort.bam']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# MACS will save fragment pileup signal per million reads

INFO  @ Fri, 10 Jun 2022 07:41:06: #1 read tag files...
INFO  @ Fri, 10 Jun 2022 07:41:06: #1 read treatment tags...
INFO  @ Fri, 10 Jun 2022 07:41:13:  1000000
INFO  @ Fri, 10 Jun 2022 07:41:19:  2000000
INFO  @ Fri, 10 Jun 2022 07:41:25:  3000000
INFO  @ Fri, 10 Jun 2022 07:41:31:  4000000
INFO  @ Fri, 10 Jun 2022 07:41:37:  5000000
INFO  @ Fri, 10 Jun 2022 07:41:43:  6000000
INFO  @ Fri, 10 Jun 2022 07:41:49:  7000000
INFO  @ Fri, 10 Jun 2022 07:41:56:  8000000
INFO  @ Fri, 10 Jun 2022 07:42:02:  9000000
INFO  @ Fri, 10 Jun 2022 07:42:08:  10000000
INFO  @ Fri, 10 Jun 2022 07:42:14:  11000000
INFO  @ Fri, 10 Jun 2022 07:42:20:  12000000
INFO  @ Fri, 10 Jun 2022 07:42:26:  13000000
INFO  @ Fri, 10 Jun 2022 07:42:32:  14000000
INFO  @ Fri, 10 Jun 2022 07:42:38:  15000000
INFO  @ Fri, 10 Jun 2022 07:42:44:  16000000
INFO  @ Fri, 10 Jun 2022 07:42:51:  17000000
INFO  @ Fri, 10 Jun 2022 07:42:57:  18000000
INFO  @ Fri, 10 Jun 2022 07:43:03:  19000000
INFO  @ Fri, 10 Jun 2022 07:43:10:  20000000
Traceback (most recent call last):
  File "/apps/software/gcc-6.2.0/macs2/2.1.0/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.0.20150420', 'macs2')
  File "/apps/software/gcc-6.2.0/python/2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/apps/software/gcc-6.2.0/python/2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/apps/software/gcc-6.2.0/macs2/2.1.0/lib/python2.7/site-packages/MACS2-2.1.0.20150420-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 614, in <module>

  File "/apps/software/gcc-6.2.0/macs2/2.1.0/lib/python2.7/site-packages/MACS2-2.1.0.20150420-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main

  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 70, in run
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 400, in load_tag_files_options
  File "MACS2/IO/Parser.pyx", line 888, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12930)
  File "MACS2/IO/Parser.pyx", line 892, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12878)
  File "MACS2/IO/Parser.pyx", line 961, in MACS2.IO.Parser.BAMParser.__append_fwtrack_wo_pysam (MACS2/IO/Parser.c:14106)
  File "MACS2/IO/FixWidthTrack.pyx", line 130, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3181)
  File "MACS2/IO/FixWidthTrack.pyx", line 149, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3040)
IndexError: index 536248 is out of bounds for axis 0 with size 536248
```
