### ISSUE TITLE
Getting traceback with bdgcmp 

### ISSUE THREAD

**Issue by msxakk** [taoliu/MACS#85]
Dear developers,

I'm trying to create a continuous coverage signal by comparing ChIP bedGraph to control bedGraph using bdgcmp option. For that purpose I'm using macs2 generated _control_lambde.bdg and _treat_pileup.bdg . 
The command and traceback shown here:

macs2 bdgcmp -t s_treat_pileup.bdg -c s_control_lambda.bdg --outdir fold_enrichment_above_input_bdg -o s.bdg -m FE
INFO  @ Fri, 03 Jul 2015 15:03:39: Read and build treatment bedGraph... 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 614, in <module>
    main()
  File "/usr/local/bin/macs2", line 72, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/bdgcmp_cmd.py", line 40, in run
    tbtrack = tbio.build_bdgtrack()
  File "MACS2/IO/BedGraphIO.pyx", line 108, in MACS2.IO.BedGraphIO.bedGraphIO.build_bdgtrack (MACS2/IO/BedGraphIO.c:1257)
IndexError: list index out of range

Any help?

**Comment by taoliu** [comment]
It seems the s_treat_pileup.bdg file is broken. Could you check the last few lines of the 's_treat_pileup.bdg' file to see if they all have FOUR columns? You can use 'tail -10 s_treat_pileup.bdg' command in Linux.

**Comment by taoliu** [comment]
Close due to inactivity. Reopen if needed.

**Comment by hlk123** [comment]
Hi everyone,

I assume, that I might have the same problem?

When performing bdgdiff using MACS2 for ChIP-Seq data following error occurs shortly after starting the procedure: "IndexError: list index out of range"

_MacBook-Air: xxx_bdgdiff $ macs2 bdgdiff --t1 cond1_treat_pileup.bdg --c1 cond1_control_lambda.bdg --t2 cond2_treat_pileup.bdg --c2 cond2_peaks_control_lambda.bdg --d1 76813950 --d2 67194613 -g 60 -l 200 --o-prefix diff_cond1_vs_cond2
INFO @ Mon, 10 Dec 2018 09:34:23: Read and build treatment 1 bedGraph...
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/2.7/bin/macs2", line 4, in 
import('pkg_resources').run_script('MACS2==2.1.2', 'macs2')
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/init.py", line 658, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/init.py", line 1445, in run_script
exec(script_code, namespace, namespace)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MACS2-2.1.2-py2.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/macs2", line 622, in

File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MACS2-2.1.2-py2.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/macs2", line 93, in main

File "build/bdist.macosx-10.9-x86_64/egg/MACS2/bdgdiff_cmd.py", line 60, in run
File "MACS2/IO/BedGraphIO.pyx", line 108, in MACS2.IO.BedGraphIO.bedGraphIO.build_bdgtrack (MACS2/IO/BedGraphIO.c:1213)
IndexError: list index out of range_

I installed the latest versions of MACS and Python.
Callpeaks just worked fine before.
Does anyone have an idea on how to solve the problem?
Thank you in advance!

Leo
