### ISSUE TITLE
macs2 filterdup fails

### ISSUE THREAD

**Issue by tjsavitsky** [taoliu/MACS#87]
I tried changing the references of 'cProb' to 'Prob' in both diffpeak_cmd.py and filterdup_cmd.py.  Is this advisable?  I was getting the following error:

Traceback (most recent call last):
  File "/data/local/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.0.20150603', 'macs2')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/data/local/lib/python2.7/site-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 614, in <module>
    main()
  File "/data/local/lib/python2.7/site-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 87, in main
    from MACS2.filterdup_cmd import run
  File "/data/local/lib/python2.7/site-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/MACS2/filterdup_cmd.py", line 29, in <module>
    from MACS2.cProb import binomial_cdf_inv
ImportError: No module named cProb

**Comment by taoliu** [comment]
Thanks for reporting this issue. It has been fixed in 1123c07. BTW, 'diffpeak' command has been retired and been replaced by 'bdgdiff'.

**Comment by jlpulice** [comment]
I updated my MACS2 version today using PyPI and it created this problem. What is going on?

**Comment by taoliu** [comment]
@jlpulice Remove your old installation ENTIRELY first. There is no reference to cProb right now. If you saw it, that means the your filterdup_cmd script was from older version. This issue will happen if you install MACS2 using the codes from Github instead of using 'pip'. 'pip install -U' is supposed to remove old installation before installing new one.

https://github.com/taoliu/MACS/blob/master/MACS2/filterdup_cmd.py

**Comment by jlpulice** [comment]
I got it fixed, I'm using Ubuntu and I forgot to use the -H parameter with sudo so it was installing the new version for the root user only. It's working fine now. Thanks!!
