### ISSUE TITLE
'MACS2.IO.Parser.BAMPEParser' object has no attribute 'finalize'

### ISSUE THREAD

**Issue by ebookehbio** [taoliu/MACS#88]
Dear Tao,

Thanks for the great software. 

However, when running test command for PE-reads (current github version), this error appears. Could you help to solve it?

Thanks!

Chen Tong
```
macs2 callpeak -f BAMPE -t $CHIPPE -c $CTRLPE -n run_callpeak_pe_narrow -B --outdir run_callpeak_pe_narrow --call-summits &> run_callpeak_pe_narrow/run_callpeak_pe_narrow.log

cat run_callpeak_pe_narrow/run_callpeak_pe_narrow.log
INFO  @ Sun, 19 Jul 2015 10:56:00: 
# Command line: callpeak -f BAMPE -t CTCF_PE_ChIP_chr22.bam -c CTCF_PE_CTRL_chr22.bam -n run_callpeak_pe_narrow -B --outdir run_callpeak_pe_narrow --call-summits
# ARGUMENTS LIST:
# name = run_callpeak_pe_narrow
# format = BAMPE
# ChIP-seq file = ['CTCF_PE_ChIP_chr22.bam']
# control file = ['CTCF_PE_CTRL_chr22.bam']
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
# Searching for subpeak summits is on
 
INFO  @ Sun, 19 Jul 2015 10:56:00: #1 read fragment files... 
INFO  @ Sun, 19 Jul 2015 10:56:00: #1 read treatment fragments... 
Traceback (most recent call last):
  File "/home/chentong/anaconda/bin/macs2", line 5, in <module>
    pkg_resources.run_script('MACS2==2.1.0.20150603', 'macs2')
  File "/home/chentong/anaconda/lib/python2.7/site-packages/setuptools-3.6-py2.7.egg/pkg_resources.py", line 534, in run_script
  File "/home/chentong/anaconda/lib/python2.7/site-packages/setuptools-3.6-py2.7.egg/pkg_resources.py", line 1434, in run_script
  File "/home/chentong/anaconda/lib/python2.7/site-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 614, in <module>
    main()
  File "/home/chentong/anaconda/lib/python2.7/site-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main
    run( args )
  File "/home/chentong/anaconda/lib/python2.7/site-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 69, in run
    if options.PE_MODE: (treat, control) = load_frag_files_options (options)
  File "/home/chentong/anaconda/lib/python2.7/site-packages/MACS2-2.1.0.20150603-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 363, in load_frag_files_options
    tp.finalize()
AttributeError: 'MACS2.IO.Parser.BAMPEParser' object has no attribute 'finalize'
```

**Comment by taoliu** [comment]
Thanks for the feedback! Fixed in b120c03. Please remove old installation entirely, then reinstall. If you see the same issue, please report back. Thank you again!
