### ISSUE TITLE
Problem with multiple input files

### ISSUE THREAD

**Issue by dariober** [taoliu/MACS#93]
Hello,

Previous versions of macs allowed multiple input files as documented in the -t and -c options. 
In version macs2 2.1.0.20150420 I get the following error:
```
macs2 callpeak -t pd.tmp.bam -n tmp   ## OK
macs2 callpeak -t pd1.tmp.bam -n tmp  ## OK

macs2 callpeak -t pd.tmp.bam pd1.tmp.bam -n tmp

INFO  @ Fri, 07 Aug 2015 11:32:40: 
# Command line: callpeak -t pd.tmp.bam pd1.tmp.bam -n tmp
# ARGUMENTS LIST:
# name = tmp
# format = AUTO
# ChIP-seq file = ['pd.tmp.bam', 'pd1.tmp.bam']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
 
INFO  @ Fri, 07 Aug 2015 11:32:40: #1 read tag files... 
INFO  @ Fri, 07 Aug 2015 11:32:40: #1 read treatment tags... 
INFO  @ Fri, 07 Aug 2015 11:32:40: Detected format is: BAM 
INFO  @ Fri, 07 Aug 2015 11:32:40: * Input file is gzipped. 
INFO  @ Fri, 07 Aug 2015 11:32:40: Detected format is: BAM 
INFO  @ Fri, 07 Aug 2015 11:32:40: * Input file is gzipped. 
Traceback (most recent call last):
  File "/home/berald01/.local/bin/macs2", line 5, in <module>
    pkg_resources.run_script('MACS2==2.1.0.20150420', 'macs2')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 488, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1345, in run_script
  File "/home/berald01/.local/lib/python2.7/site-packages/MACS2-2.1.0.20150420-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 614, in <module>
    
  File "/home/berald01/.local/lib/python2.7/site-packages/MACS2-2.1.0.20150420-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main
    
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 70, in run
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 400, in load_tag_files_options
  File "MACS2/IO/Parser.pyx", line 888, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12930)
  File "MACS2/IO/Parser.pyx", line 892, in MACS2.IO.Parser.BAMParser.append_fwtrack (MACS2/IO/Parser.c:12878)
  File "MACS2/IO/Parser.pyx", line 961, in MACS2.IO.Parser.BAMParser.__append_fwtrack_wo_pysam (MACS2/IO/Parser.c:14106)
  File "MACS2/IO/FixWidthTrack.pyx", line 130, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3181)
  File "MACS2/IO/FixWidthTrack.pyx", line 149, in MACS2.IO.FixWidthTrack.FWTrack.add_loc (MACS2/IO/FixWidthTrack.c:3040)
IndexError: index 1311 is out of bounds for axis 0 with size 1311
```
PS: I tried to download the current version in the repository but compilation fails since gcc can't find file ```MACS2/Prob.c```
```
python setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to MACS2.egg-info/requires.txt
writing MACS2.egg-info/PKG-INFO
writing top-level names to MACS2.egg-info/top_level.txt
writing dependency_links to MACS2.egg-info/dependency_links.txt
reading manifest file 'MACS2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'MANIFEST'
writing manifest file 'MACS2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'MACS2.Prob' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/berald01/.local/lib/python2.7/site-packages/numpy/core/include -I/home/berald01/.local/include/python2.7 -c MACS2/Prob.c -o build/temp.linux-x86_64-2.7/MACS2/Prob.o -w -O3
gcc: MACS2/Prob.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1
```

Thanks!
Dario

**Comment by taoliu** [comment]
Try "pip install -U MACS2". Or if you want to install MACS2 from github codes,  install cython first then use 'python setup_w_cython.py install'.

Also: https://github.com/taoliu/MACS/wiki/Install-macs2
